### PR TITLE
rtl8812au ct bump to fix compile for linux 6.1

### PR DESCRIPTION
**Pull request by john-tho**
rtl8812au ct bump to fix compile for linux 6.1
Not recently compile tested…

### CODE REVIEW

**Comment by Ansuel** [comment]
@john-tho compilation error to fix!

**Comment by john-tho** [comment]
Right, backports version code. When I submitted this upstream, OpenWrt older kernels were still using older backports, so I completly missed this. Sorry.

Error for `link_id`, because I tested `LINUX_VERSION_CODE` in https://github.com/greearb/rtl8812AU_8821AU_linux/commit/a027da58e8d8e95827f97222ca321cd0b2d377dd
The 100-api-update OpenWrt patch changed these without adding version test: https://github.com/openwrt/openwrt/commit/03518a1b3a565c74391ddfe0d5bfb352994141ef

The quick fix: Remove the version checks I added.
A thorough fix? It looks like backports defines a backported version via `CPTCFG_KERNEL_VERSION`, but an example from my `build_dir` looks like a full git version:

```
compat_version:compat-wireless-6.1.24-4-r23078+63-e81298463ed4
versions:BACKPORTED_KERNEL_VERSION="v6.1.24-0-g0102425ac76b"
Makefile.kernel:	-DCPTCFG_KERNEL_VERSION=\"$(BACKPORTED_KERNEL_VERSION)\" \
```

https://git.kernel.org/pub/scm/linux/kernel/git/backports/backports.git/tree/backport/backport-include/linux/version.h?id=e2d7896795bed7483fb08ff47801afdbd7cd9849

I cannot find an example use of this `CPTCFG_KERNEL_VERSION`.
Adding `CPTCFG_VERSION_CODE` to backports in the style of `LINUX_VERSION_CODE` would make this simple.
https://elixir.bootlin.com/linux/latest/source/Makefile#L1331

I came up with a dirty perl script that should give me a version code from this:
```
echo v6.11.24-0-g0102425ac76b | perl -n -e '/.*([[:digit:]])+\.([[:digit:]]+)\.([[:digit:]]+).*/; if($1 and $2>=0 and $3>=0) {my $version=$1; my $patchlevel=$2; my $sublevel=$3; if($sublevel>255) {$sublevel = 255} my $versioncode=($version<<16)+($patchlevel<<8)+($sublevel); print "$versioncode\n"}'
396056
```
Would _something_ like this be appropriate to add to the backports Makefile.kernel to provide me a useable backports version?


The `Werror=incompatible-pointer-types`:
```
  make[3] -C package/kernel/rtl8812au-ct compile
    ERROR: package/kernel/rtl8812au-ct failed to build.
make -r world: build failed. Please re-run make with -j1 V=s or V=sc for a higher verbosity level to see what's going on
make: *** [/__w/openwrt/openwrt/openwrt/include/toplevel.mk:231: world] Error 1
====== Make errors from logs/package/kernel/rtl8812au-ct/compile.txt ======
/__w/openwrt/openwrt/openwrt/build_dir/target-x86_64-openwrt-linux-musl_musl/linux-x86_64/rtl8812au-ct-2022-10-26-9b2b203a/os_dep/linux/ioctl_cfg80211.c:5974:20: note: (near initialization for 'rtw_cfg80211_ops.del_key')
/__w/openwrt/openwrt/openwrt/build_dir/target-x86_64-openwrt-linux-musl_musl/linux-x86_64/rtl8812au-ct-2022-10-26-9b2b203a/os_dep/linux/ioctl_cfg80211.c:5975:28: error: initialization of 'int (*)(struct wiphy *, struct net_device *, int,  u8,  bool,  bool)' {aka 'int (*)(struct wiphy *, struct net_device *, int,  unsigned char,  _Bool,  _Bool)'} from incompatible pointer type 'int (*)(struct wiphy *, struct net_device *, u8,  bool,  bool)' {aka 'int (*)(struct wiphy *, struct net_device *, unsigned char,  _Bool,  _Bool)'} [-Werror=incompatible-pointer-types]
 5975 |         .set_default_key = cfg80211_rtw_set_default_key,
      |                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/__w/openwrt/openwrt/openwrt/build_dir/target-x86_64-openwrt-linux-musl_musl/linux-x86_64/rtl8812au-ct-2022-10-26-9b2b203a/os_dep/linux/ioctl_cfg80211.c:5975:28: note: (near initialization for 'rtw_cfg80211_ops.set_default_key')
/__w/openwrt/openwrt/openwrt/build_dir/target-x86_64-openwrt-linux-musl_musl/linux-x86_64/rtl8812au-ct-2022-10-26-9b2b203a/os_dep/linux/ioctl_cfg80211.c:6001:20: error: initialization of 'int (*)(struct wiphy *, struct net_device *, unsigned int)' from incompatible pointer type 'int (*)(struct wiphy *, struct net_device *)' [-Werror=incompatible-pointer-types]
 6001 |         .stop_ap = cfg80211_rtw_stop_ap,
      |                    ^~~~~~~~~~~~~~~~~~~~
/__w/openwrt/openwrt/openwrt/build_dir/target-x86_64-openwrt-linux-musl_musl/linux-x86_64/rtl8812au-ct-2022-10-26-9b2b203a/os_dep/linux/ioctl_cfg80211.c:6001:20: note: (near initialization for 'rtw_cfg80211_ops.stop_ap')
cc1: all warnings being treated as errors
```

**Comment by guidosarducci** [comment]
@john-tho Thanks, the error I ran into for #12705, seems addressed by your patches. I'll try rebuilding with them...
```
/home/kodidev/openwrt-project/build_dir/target-aarch64_cortex-a53_musl/linux-armvirt_64/rtl8812au-ct-2021-11-07-39df5596/core/rtw_cmd.c
In file included from /home/kodidev/openwrt-project/build_dir/target-aarch64_cortex-a53_musl/linux-armvirt_64/rtl8812au-ct-2021-11-07-39df5596/include/osdep_service.h:41,
                 from /home/kodidev/openwrt-project/build_dir/target-aarch64_cortex-a53_musl/linux-armvirt_64/rtl8812au-ct-2021-11-07-39df5596/include/drv_types.h:32,
                 from /home/kodidev/openwrt-project/build_dir/target-aarch64_cortex-a53_musl/linux-armvirt_64/rtl8812au-ct-2021-11-07-39df5596/core/rtw_cmd.c:22:
/home/kodidev/openwrt-project/build_dir/target-aarch64_cortex-a53_musl/linux-armvirt_64/rtl8812au-ct-2021-11-07-39df5596/core/rtw_cmd.c: In function 'rtw_cmd_thread':
/home/kodidev/openwrt-project/build_dir/target-aarch64_cortex-a53_musl/linux-armvirt_64/rtl8812au-ct-2021-11-07-39df5596/include/osdep_service_linux.h:166:23: error: implicit declaration of function 'complete_and_exit' [-Werror=implicit-function-declaration]
  166 | #define thread_exit() complete_and_exit(NULL, 0)
      |                       ^~~~~~~~~~~~~~~~~
/home/kodidev/openwrt-project/build_dir/target-aarch64_cortex-a53_musl/linux-armvirt_64/rtl8812au-ct-2021-11-07-39df5596/core/rtw_cmd.c:706:9: note: in expansion of macro 'thread_exit'
  706 |         thread_exit();
      |         ^~~~~~~~~~~
/home/kodidev/openwrt-project/build_dir/target-aarch64_cortex-a53_musl/linux-armvirt_64/rtl8812au-ct-2021-11-07-39df5596/core/rtw_cmd.c:708:1: error: control reaches end of non-void function [-Werror=return-type]
  708 | }
      | ^
cc1: all warnings being treated as errors
```

**Comment by ynezz** [comment]
@john-tho thanks for the fix, any reason for "marked this pull request as draft last week" ? I've hit that [build issue on the CI as well](https://github.com/openwrt/openwrt/actions/runs/5177146361/jobs/9330242854#step:31:532) so I would like to merge this fix if it builds fine.

**Comment by john-tho** [comment]
PR was marked draft while I tried to find a clean and easy way to test against the backported kernel version, but I did not find one. I guess @hauke would be the one to ask? Best I came up (but did not implement) with was doing the same as Linux; building a header file which defines the version from the backports Makefile.kernel.
If we don't mind the workaround (revert my upstream link_id patch, and additionally continue to use our downstream patch), it should be good to go.
Cheers

**Comment by pkgadd** [comment]
hmm, while working on x86_64/ v6.1, I stumbled over this as well - for me, just updating the upstream version and dropping [100-api_update.patch](https://github.com/openwrt/openwrt/blob/main/package/kernel/rtl8812au-ct/patches/100-api_update.patch) (so without 099-cut-linkid-linux-version-code-conditionals.patch) seemed to work just fine.

**Comment by hauke** [comment]
Probably adding a define with the version in backports would be nice. When I find some time I will have a look at this. I think we mostly hard coded such thing in patches for the wifi drivers in OpenWrt.
@pkgadd suggestion sounds good. Does it compile with kernel 5.15 and with 6.1?

**Comment by john-tho** [comment]
> Probably adding a define with the version in backports would be nice. When I find some time I will have a look at this. I think we mostly hard coded such thing in patches for the wifi drivers in OpenWrt.

Thanks Hauke,
I had a dig at this, and came up with (bit of a hack based on Linux Makefile version.h): https://github.com/john-tho/openwrt/pull/6/commits/5fc52884022d440944263f44b8ed3efa30782b34, which let me test `BACKPORTED_LINUX_VERSION_CODE` in this driver. Test PR here: https://github.com/john-tho/openwrt/pull/6. It seemed to compile for me on 5.15. Let me know what you think, or feel free to improve and use, or if I should submit the backports change somewhere else?

> just updating the upstream version and dropping [100-api_update.patch](https://github.com/openwrt/openwrt/blob/main/package/kernel/rtl8812au-ct/patches/100-api_update.patch) (so without 099-cut-linkid-linux-version-code-conditionals.patch) seemed to work just fine.
> @pkgadd suggestion sounds good. Does it compile with kernel 5.15 and with 6.1?

That won't work for 5.15, because (upstream) I tested against `LINUX_VERSION_CODE` (5.15), but we backport 6.1 80211 changes.

Cheers,

**Comment by hauke** [comment]
Thanks for the pull request. I will try to find some time to look into Linux backports to allow Linux backports version detection I also saw that other vendors sometimes need such checks.
