### PR TITLE
toolchain: binutils: fix compilation with GCC15

### LINKED ISSUE #18678: Compilation error - Need upgrade of binutils to recent package
### Describe the bug

Error got:

```
In file included from mips-opc.c:29:
mips-opc.c: In function 'decode_mips_operand':
mips-formats.h:86:7: error: expected identifier or '(' before 'static_assert'
   86 |       static_assert[(1 << (SIZE)) == ARRAY_SIZE (MAP)]; \
      |       ^~~~~~~~~~~~~
mips-opc.c:214:15: note: in expansion of macro 'MAPPED_REG'
  214 |     case 'z': MAPPED_REG (0, 0, GP, reg_0_map);
      |               ^~~~~~~~~~
make[8]: *** [Makefile:1077: mips-opc.lo] Error 1
make[8]: Leaving directory '/files/src/openwrt/kuwfi830/build_dir/toolchain-mips_24kc_gcc-14.2.0_musl/binutils-2.42/opcodes'
```

### OpenWrt version

Not relevant

### OpenWrt release

Not relevant

### OpenWrt target/subtarget

Not relevant

### Device

Not relevant

### Image kind

Official downloaded image

### Steps to reproduce

Build with GCC 15.1

### Actual behaviour

Not compiling

### Expected behaviour

Compiling

### Additional info

_No response_

### Diffconfig

```text

```

### Terms

- [x] I am reporting an issue for OpenWrt, not an unsupported fork.

### PR DESCRIPTION
**Pull request by robimarko**
GCC15 has switched the C language default from GNU17 to GNU23[1] and this causes builds to fail with:
```
In file included from mips-opc.c:29:
mips-opc.c: In function 'decode_mips_operand':
mips-formats.h:86:7: error: expected identifier or '(' before 'static_assert'
   86 |       static_assert[(1 << (SIZE)) == ARRAY_SIZE (MAP)]; \
      |       ^~~~~~~~~~~~~
mips-opc.c:214:15: note: in expansion of macro 'MAPPED_REG'
  214 |     case 'z': MAPPED_REG (0, 0, GP, reg_0_map);
      |               ^~~~~~~~~~
```

So, backport upstream fix for this[2] to fix compilation with GCC15. Patch for 2.40 was manually refreshed as part of the S390 code does not exist in 2.40 as it was added after it.

[1] https://gcc.gnu.org/gcc-15/porting_to.html#c23
[2] https://sourceware.org/git/?p=binutils-gdb.git;a=commit;h=8ebe62f3f0d27806b1bf69f301f5e188b4acd2b4

Fixes: #18678

### CODE REVIEW

**Comment by robimarko** [comment]
Thanks! Rebased on top of main and merged!
