### ISSUE TITLE
Compilation error - Need upgrade of binutils to recent package

### ISSUE THREAD

**Issue by grosjo** [openwrt/openwrt#18678]
### Describe the bug

Error got:

```
In file included from mips-opc.c:29:
mips-opc.c: In function 'decode_mips_operand':
mips-formats.h:86:7: error: expected identifier or '(' before 'static_assert'
   86 |       static_assert[(1 << (SIZE)) == ARRAY_SIZE (MAP)]; \
      |       ^~~~~~~~~~~~~
mips-opc.c:214:15: note: in expansion of macro 'MAPPED_REG'
  214 |     case 'z': MAPPED_REG (0, 0, GP, reg_0_map);
      |               ^~~~~~~~~~
make[8]: *** [Makefile:1077: mips-opc.lo] Error 1
make[8]: Leaving directory '/files/src/openwrt/kuwfi830/build_dir/toolchain-mips_24kc_gcc-14.2.0_musl/binutils-2.42/opcodes'
```

### OpenWrt version

Not relevant

### OpenWrt release

Not relevant

### OpenWrt target/subtarget

Not relevant

### Device

Not relevant

### Image kind

Official downloaded image

### Steps to reproduce

Build with GCC 15.1

### Actual behaviour

Not compiling

### Expected behaviour

Compiling

### Diffconfig

```text

```

### Terms

- [x] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by grosjo** [comment]
Porbably upgrade bintuiles to 2.44 (latest) ?

**Comment by grosjo** [comment]
@robimarko still not enough

Error:
```
In file included from mips-opc.c:29:
mips-opc.c: In function 'decode_mips_operand':
mips-formats.h:86:7: error: expected identifier or '(' before 'static_assert'
   86 |       static_assert((1 << (SIZE)) == ARRAY_SIZE (MAP)); \
      |       ^~~~~~~~~~~~~
mips-opc.c:214:15: note: in expansion of macro 'MAPPED_REG'
  214 |     case 'z': MAPPED_REG (0, 0, GP, reg_0_map);
      |               ^~~~~~~~~~



```

**Comment by robimarko** [comment]
It has to be enough, I had the exact same issue and backport fixed it.

You gotta do make toolchain/binutils/clean do though first
