### ISSUE TITLE
tools libressl 3.7.3 upgrade to 4.1.0 result in multiple definition of `ecdsa_sign' clash

### ISSUE THREAD

**Issue by vincentmli** [openwrt/openwrt#20842]
### Describe the bug

Hi, 

I have loongarch build machine to build openwrt and only libressl 4.1.0 started to support loongarch, so I upgraded libressl from 3.7.3 to 4.1.0
```
diff --git a/tools/libressl/Makefile b/tools/libressl/Makefile
index 4072194763..33f642dde9 100644
--- a/tools/libressl/Makefile
+++ b/tools/libressl/Makefile
@@ -8,8 +8,8 @@
 include $(TOPDIR)/rules.mk
 
 PKG_NAME:=libressl
-PKG_VERSION:=3.7.3
-PKG_HASH:=7948c856a90c825bd7268b6f85674a8dcd254bae42e221781b24e3f8dc335db3
+PKG_VERSION:=4.1.0
+PKG_HASH:=0f71c16bd34bdaaccdcb96a5d94a4921bfb612ec6e0eba7a80d8854eefd8bb61
 
 PKG_CPE_ID:=cpe:/a:openbsd:libressl
```
but this result in SSL clash as below when building tools/mkimage
```
  HOSTLD  tools/dumpimage
/usr/bin/ld: /usr/src/openwrt/staging_dir/host/lib/libcrypto.a(libcrypto_la-ecdsa.o): in function `ecdsa_sign':
ecdsa.c:(.text+0xd50): multiple definition of `ecdsa_sign'; tools/generated/lib/ecdsa/ecdsa-libcrypto.o:ecdsa-libcrypto.c:(.text+0xab0): first defined here
/usr/bin/ld: /usr/src/openwrt/staging_dir/host/lib/libcrypto.a(libcrypto_la-ecdsa.o): in function `ecdsa_verify':
ecdsa.c:(.text+0x12d0): multiple definition of `ecdsa_verify'; tools/generated/lib/ecdsa/ecdsa-libcrypto.o:ecdsa-libcrypto.c:(.text+0xc30): first defined here
collect2: error: ld returned 1 exit status
make[5]: *** [scripts/Makefile.host:106: tools/dumpimage] Error 1
make[4]: *** [Makefile:2434: tools-only] Error 2
make[4]: Leaving directory '/usr/src/openwrt/build_dir/host/u-boot-2025.10'
make[3]: *** [Makefile:54: /usr/src/openwrt/build_dir/host/u-boot-2025.10/.built] Error 2
make[3]: Leaving directory '/usr/src/openwrt/tools/mkimage'
time: tools/mkimage/compile#10.20#1.46#11.67
    ERROR: tools/mkimage failed to build.
```

this same issue happens to both x86 and loongarch build machine after upgrading libressl to 4.1.0. is there a better way to upgrade libressl to 4.1.0 without breaking tools/mkimage build?

The detail is here [https://forum.openwrt.org/t/loongarch64-libressl-fatal-error-bn-arch-h-no-such-file-or-directory/243194](https://forum.openwrt.org/t/loongarch64-libressl-fatal-error-bn-arch-h-no-such-file-or-directory/243194)

### OpenWrt version

v24.10.4

### OpenWrt release

v24.10.4

### OpenWrt target/subtarget

loongarch

### Device

loongson 3a6000 mini PC

### Image kind

Self-built image

### Steps to reproduce

git clone https://github.com/openwrt/openwrt.git
cd openwrt
./scripts/feeds update -a
./scripts/feeds install -a

make menuconfig to select loongarch target

change tools/libressl/Makefile to 4.1.0

make defconfig download clean

FORCE_UNSAFE_CONFIGURE=1 make -j6 V=s world

### Actual behaviour

tools/mkimage build failure

### Expected behaviour

tools/mkimage build success

### Diffconfig

```text
./scripts/diffconfig.sh
CONFIG_TARGET_loongarch64=y
CONFIG_TARGET_loongarch64_generic=y
CONFIG_TARGET_loongarch64_generic_DEVICE_generic=y
```

### Terms

- [x] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by vincentmli** [comment]
it looks there is libressl 4.0.0 upgrade commit https://github.com/hardfalcon/openwrt/commit/dc6debe7113e26db6252009a55cf8a37e0e668a8, maybe similar patch could applied to 4.1.0?

**Comment by vincentmli** [comment]
it looks 4.0.0 update causes fakeroot segfault, I observed same segfault with other workaround too

```
commit 6ac09b940fcdef052fff3a2819a8ee7d44f92776
Author: Robert Marko <robimarko@gmail.com>
Date:   Sat Mar 29 19:23:15 2025 +0100

    Revert "tools/libressl: update to 4.0.0"
    
    This reverts commit 21cece29e9eebc397eadee259e60c7fc44828cce.
    
    Unfortunately, LibreSSL 4.0 causes the host APK tools to segfault under
    fakeroot when .apk is being generated and it is completely breaking
    building under Debian and Ubuntu hosts.
    
    So, until this is fixed lets revert the update.
    
    Signed-off-by: Robert Marko <robimarko@gmail.com>
```

**Comment by brada4** [comment]
Can you make a single package build log with -j1 so that we see how same object is compiled twice? there must be explicit line in upstream makefiles doing it, make could not accidentally decide to compile something 2x - the typical compilation is source -> object and re-doing same object if mtime on 1st went up.

**Comment by neheb** [comment]
That fakeroot crash was actually in apk. Fixed in https://github.com/openwrt/openwrt/commit/8e5db148e96be5d1f17b6babfd445727714fdffc

https://github.com/openwrt/openwrt/pull/19562 has a fix for u-boot.

**Comment by vincentmli** [comment]
@neheb so if I pull the most recent `main` branch now, it should be fixed?

**Comment by vincentmli** [comment]
@neheb I will wait for https://github.com/openwrt/openwrt/pull/19562 to get merged, thanks for the heads up :)

**Comment by neheb** [comment]
@vincentmli this can be closed now.
