### PR TITLE
uboot-mediatek: add noncached_set_region prototype to fix build

### PR DESCRIPTION
**Pull request by jonasjelonek**
After the update of uboot-mediatek to v2024.10 in f8c22c9bff, build fails with the following error when using GCC-14:
cmd/cache.c: In function 'do_dcache':
cmd/cache.c:57:25: error: implicit declaration of function
	'noncached_set_region' [-Wimplicit-function-declaration]

It is caused by an upstream commit ( [7d6cee2cd](https://github.com/u-boot/u-boot/commit/7d6cee2cd0e2e2507aca1e3a6fe0e2cb241a116e) ) removing weak function declarations in favor of arch-specific definitions.
The issue is already discussed in #16697 where I also proposed this fix for the issue.
It is also reported upstream [here](https://source.denx.de/u-boot/u-boot/-/issues/42). This PR is intended as a temporary fix until the issue is resolved upstream.

### CODE REVIEW

**Comment by jonasjelonek** [comment]
ping @dangowrt

**Review by N-Storm — APPROVED** [review]
Confirmed to work and fixing builds with gcc-14 on a Debian-12 based x86_64 host with recent OpenWRT snapshot and vanilla u-boot as well.
