### PR TITLE
CI: Build all targets on changes

### PR DESCRIPTION
**Pull request by hauke**
CI: Build all targets on changes

This builds the target in case anything changes in target specific code.
This will build all subtargets and activate all boards.

This also builds the testing kernel if it is available.

If there is no external toolchain the toolchain will be build in the
target build process.

All the .github/workflows/target-*.yml files are automatically
generated. Building all targets takes multiple hours even with 20
builders, this only triggers a target build in case something changed
for this specific target. An own workflow file is added for each target
which triggers on pull requests and also earlier when some changes are
pushed to a branch on github. The labeler is not working on branch pushes.

This should help detect build problems when new boards are added or when
some changes are done to a target.

In addition I am also fixing some bugs before and make the existing workflows more reusable.

### CODE REVIEW

**Comment by hauke** [comment]
The build fail in the lantiq build is fixed in #11144.

broadcom-wl is not compiling on kernel 5.15 any more:
```
make[4]: Entering directory '/home/hauke/openwrt/openwrt/build_dir/target-mips_mips32_musl/linux-bcm63xx_generic/linux-5.15.76'
  CC [M]  /home/hauke/openwrt/openwrt/build_dir/target-mips_mips32_musl/linux-bcm63xx_generic/broadcom-wl-5.10.56.27.3/driver/wl_iw.o
/home/hauke/openwrt/openwrt/build_dir/target-mips_mips32_musl/linux-bcm63xx_generic/broadcom-wl-5.10.56.27.3/driver/wl_iw.c: In function 'dev_wlc_ioctl':
/home/hauke/openwrt/openwrt/build_dir/target-mips_mips32_musl/linux-bcm63xx_generic/broadcom-wl-5.10.56.27.3/driver/wl_iw.c:121:14: error: implicit declaration of function 'get_fs'; did you mean 'sget_fc'? [-Werror=implicit-function-declaration]
  121 |         fs = get_fs();
      |              ^~~~~~
      |              sget_fc
/home/hauke/openwrt/openwrt/build_dir/target-mips_mips32_musl/linux-bcm63xx_generic/broadcom-wl-5.10.56.27.3/driver/wl_iw.c:121:14: error: incompatible types when assigning to type 'mm_segment_t' from type 'int'
/home/hauke/openwrt/openwrt/build_dir/target-mips_mips32_musl/linux-bcm63xx_generic/broadcom-wl-5.10.56.27.3/driver/wl_iw.c:122:9: error: implicit declaration of function 'set_fs'; did you mean 'sget_fc'? [-Werror=implicit-function-declaration]
  122 |         set_fs(KERNEL_DS);
      |         ^~~~~~
      |         sget_fc
/home/hauke/openwrt/openwrt/build_dir/target-mips_mips32_musl/linux-bcm63xx_generic/broadcom-wl-5.10.56.27.3/driver/wl_iw.c:122:16: error: 'KERNEL_DS' undeclared (first use in this function); did you mean 'KERNFS_NS'?
  122 |         set_fs(KERNEL_DS);
      |                ^~~~~~~~~
      |                KERNFS_NS
/home/hauke/openwrt/openwrt/build_dir/target-mips_mips32_musl/linux-bcm63xx_generic/broadcom-wl-5.10.56.27.3/driver/wl_iw.c:122:16: note: each undeclared identifier is reported only once for each function it appears in
/home/hauke/openwrt/openwrt/build_dir/target-mips_mips32_musl/linux-bcm63xx_generic/broadcom-wl-5.10.56.27.3/driver/wl_iw.c: In function 'wl_iw_set_freq':
/home/hauke/openwrt/openwrt/build_dir/target-mips_mips32_musl/linux-bcm63xx_generic/broadcom-wl-5.10.56.27.3/driver/wl_iw.c:393:9: warning: this 'if' clause does not guard... [-Wmisleading-indentation]
  393 |         if (fwrq->m > 4000 && fwrq->m < 5000)
      |         ^~
/home/hauke/openwrt/openwrt/build_dir/target-mips_mips32_musl/linux-bcm63xx_generic/broadcom-wl-5.10.56.27.3/driver/wl_iw.c:396:17: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the 'if'
  396 |                 chan = wf_mhz2channel(fwrq->m, sf);
      |                 ^~~~
cc1: some warnings being treated as errors
make[5]: *** [scripts/Makefile.build:289: /home/hauke/openwrt/openwrt/build_dir/target-mips_mips32_musl/linux-bcm63xx_generic/broadcom-wl-5.10.56.27.3/driver/wl_iw.o] Error 1
make[4]: *** [Makefile:1901: /home/hauke/openwrt/openwrt/build_dir/target-mips_mips32_musl/linux-bcm63xx_generic/broadcom-wl-5.10.56.27.3/driver] Error 2
make[4]: Leaving directory '/home/hauke/openwrt/openwrt/build_dir/target-mips_mips32_musl/linux-bcm63xx_generic/linux-5.15.76'
make[3]: *** [Makefile:186: /home/hauke/openwrt/openwrt/build_dir/target-mips_mips32_musl/linux-bcm63xx_generic/broadcom-wl-5.10.56.27.3/.built] Error 2
make[3]: Leaving directory '/home/hauke/openwrt/openwrt/package/kernel/broadcom-wl'

```

**Comment by Ansuel** [comment]
@hauke wow lots ot check...
the error with the brcm driver is a mix of Werror and the get_fs that got dropped in new kernel... I already fixed similar error for other drivers

**Comment by aparcar** [comment]
I'd try to rework the logic to drop the generator and use a matrix build instead, would that work for you?

**Comment by hauke** [comment]
I want to trigger the build of a specific target only if there are changes in that specific target because it takes 20 to 30 minutes to build and we have ~100 subtargets and kernel combinations.

Is it possible to have one workflow and trigger parts of it based on changes in a directory? For exmaple the lantiq subtargets are only getting build when something in target/linux/lantiq/ changes, but not when something in target/linux/ramips/ changes, then the ramips subtargets should get build only.

**Comment by Ansuel** [comment]
> I'd try to rework the logic to drop the generator and use a matrix build instead, would that work for you?

to have something like that you need to have a job that first parse the change in the pr (for the test) and call the right build

**Comment by ptpt52** [comment]
Please add limit on every workflow, otherwise it wastes computing resources when it is forked by others
```
if: github.repository == 'openwrt/openwrt'
```

**Comment by hauke** [comment]
> Please add limit on every workflow, otherwise it wastes computing resources when it is forked by others
> 
> ```
> if: github.repository == 'openwrt/openwrt'
> ```

I added it intentionally to push, so that people can test it already on their branch before creating the pull request. 



> > I'd try to rework the logic to drop the generator and use a matrix build instead, would that work for you?
> 
> to have something like that you need to have a job that first parse the change in the pr (for the test) and call the right build

I would like to make it also work on push already. githubs on push paths thing supports that. 
If we only want this on pull requests we could abuse the labeler and trigger it depending on the label the pull request gets.

**Comment by DragonBluep** [comment]
> > Please add limit on every workflow, otherwise it wastes computing resources when it is forked by others
> > ```
> > if: github.repository == 'openwrt/openwrt'
> > ```
> 
> I added it intentionally to push, so that people can test it already on their branch before creating the pull request.

Maybe we can add a manual trigger option `workflow_dispatch:`. I noticed that sometimes when I synchronize the upstream master branch, Actions are automatically triggered, even if this has been checked in upstream.

**Comment by aparcar** [comment]
You can dynamically create a job matrix which contains only affected targets. An example is available [here](https://github.com/aparcar/openwrt/blob/apk/.github/workflows/build-staging.yml#L26), one just have to change the logic of what to select.

**Comment by hauke** [comment]
@aparcar I do not know how to get the list of changed files. Can we get the list of changed files from the github action? If we have this we can do the matching on our own.

**Comment by Ansuel** [comment]
@hauke yes with github api we can get the hash of the base repo and the last commit and do the diff...

That was my idea... With that stuff we can parse the changed files and compose the list of things to test... Ideally with an incremental array... then pass everything as an input to the matrix list and we should have a single workflow that does all of this.

**Comment by Ansuel** [comment]
@hauke btw i'm experimenting with the idea of check the changed files... github provide API to detect that (it's only problematic for forced push event but we should NEVER care about that and we can detect forced push but I still need to find a correct way to generate hash diff)

It's a different approach but honestly your idea of overloading stuff is not bad and would result in something less complex than parsing github api... (I'm trying to skip using marketplace actions since I'm against using an action to just check changes files... but maybe we should consider that....)

My current idea is something like
- If we change stuff in target/linux/generic or Include/kernel or the workflow file, we trigger a global build and everything is tested
- If we change specific target, we parse the changes and we trigger build for only them

With all this data, we generate a matrix build.... 

@aparcar in your idea is it acceptable to use an external action to parse changed files? again things don't works well with forced push as github for some reason gives stupid hash and provide as the old hash the old commit that gets replaced by the force push....

**Comment by hauke** [comment]
I would assume that there is an API or action on the market place which can return us the changes files which is also used by github to decide to trigger an action or not, but I haven't seen any yet.

**Comment by Ansuel** [comment]
@hauke well they totally use something not public or I'm missing something... this thing would be so easy if the way they use to parse the event was public and documented...

**Comment by Ansuel** [comment]
@hauke i like the first 4 cleanup commits so i wonder if we can merge them while we discuss on how to implement this idea? (again as @aparcar said ideally it should be handled by a multisize matrix build) 

Also I wonder if build.yml should be split even more and create a configure.yml? Or it sound stupid to you?

**Comment by hauke** [comment]
I think the build has to run in one job because we heavily reuse the previous data.  

I will push the first 4 commits to master soon.

**Comment by hauke** [comment]
I merged the first 4 patches into master

**Comment by aparcar** [comment]
Here is a draft on how to do the same actions without adding multiple target files https://github.com/openwrt/openwrt/pull/12041
