### ISSUE TITLE
u-boot: fails to build with swig 4.3.0

### ISSUE THREAD

**Issue by EdiTurn** [openwrt/openwrt#17345]
### Describe the bug

u-boot fails to build after update swig to 4.3.0. 

````
make[3]: Entering directory '/home/editurn/openwrt/immortalwrt/build_dir/target-aarch64_generic_musl/u-boot-nanopi-r2s-rk3328/u-boot-2024.10'
  ENVT    include/generated/environment.h
  CC      lib/asm-offsets.s
  UPD     include/generated/generic-asm-offsets.h
  CC      arch/arm/lib/asm-offsets.s
  UPD     include/generated/asm-offsets.h
  PYMOD   rebuild
scripts/dtc/pylibfdt/libfdt_wrap.c: In function ‘_wrap_fdt_next_node’:
scripts/dtc/pylibfdt/libfdt_wrap.c:5581:17: error: too few arguments to function ‘SWIG_Python_AppendOutput’
 5581 |     resultobj = SWIG_Python_AppendOutput(resultobj, val);
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~
scripts/dtc/pylibfdt/libfdt_wrap.c:1262:1: note: declared here
 1262 | SWIG_Python_AppendOutput(PyObject* result, PyObject* obj, int is_void) {
      | ^~~~~~~~~~~~~~~~~~~~~~~~
scripts/dtc/pylibfdt/libfdt_wrap.c: In function ‘_wrap_fdt_get_mem_rsv’:
scripts/dtc/pylibfdt/libfdt_wrap.c:6388:19: error: too few arguments to function ‘SWIG_Python_AppendOutput’
 6388 |       resultobj = SWIG_Python_AppendOutput(resultobj, val);
      |                   ^~~~~~~~~~~~~~~~~~~~~~~~
scripts/dtc/pylibfdt/libfdt_wrap.c:1262:1: note: declared here
 1262 | SWIG_Python_AppendOutput(PyObject* result, PyObject* obj, int is_void) {
      | ^~~~~~~~~~~~~~~~~~~~~~~~
scripts/dtc/pylibfdt/libfdt_wrap.c:6397:19: error: too few arguments to function ‘SWIG_Python_AppendOutput’
 6397 |       resultobj = SWIG_Python_AppendOutput(resultobj, val);
      |                   ^~~~~~~~~~~~~~~~~~~~~~~~
scripts/dtc/pylibfdt/libfdt_wrap.c:1262:1: note: declared here
 1262 | SWIG_Python_AppendOutput(PyObject* result, PyObject* obj, int is_void) {
      | ^~~~~~~~~~~~~~~~~~~~~~~~
scripts/dtc/pylibfdt/libfdt_wrap.c: In function ‘_wrap_fdt_get_property_by_offset’:
scripts/dtc/pylibfdt/libfdt_wrap.c:6639:19: error: too few arguments to function ‘SWIG_Python_AppendOutput’
 6639 |       resultobj = SWIG_Python_AppendOutput(resultobj, buff);
      |                   ^~~~~~~~~~~~~~~~~~~~~~~~
scripts/dtc/pylibfdt/libfdt_wrap.c:1262:1: note: declared here
 1262 | SWIG_Python_AppendOutput(PyObject* result, PyObject* obj, int is_void) {
      | ^~~~~~~~~~~~~~~~~~~~~~~~
scripts/dtc/pylibfdt/libfdt_wrap.c: In function ‘_wrap_fdt_get_property’:
scripts/dtc/pylibfdt/libfdt_wrap.c:6702:19: error: too few arguments to function ‘SWIG_Python_AppendOutput’
 6702 |       resultobj = SWIG_Python_AppendOutput(resultobj, buff);
      |                   ^~~~~~~~~~~~~~~~~~~~~~~~
scripts/dtc/pylibfdt/libfdt_wrap.c:1262:1: note: declared here
 1262 | SWIG_Python_AppendOutput(PyObject* result, PyObject* obj, int is_void) {
      | ^~~~~~~~~~~~~~~~~~~~~~~~
scripts/dtc/pylibfdt/libfdt_wrap.c: In function ‘_wrap_fdt_get_property_w’:
scripts/dtc/pylibfdt/libfdt_wrap.c:6767:19: error: too few arguments to function ‘SWIG_Python_AppendOutput’
 6767 |       resultobj = SWIG_Python_AppendOutput(resultobj, buff);
      |                   ^~~~~~~~~~~~~~~~~~~~~~~~
scripts/dtc/pylibfdt/libfdt_wrap.c:1262:1: note: declared here
 1262 | SWIG_Python_AppendOutput(PyObject* result, PyObject* obj, int is_void) {
      | ^~~~~~~~~~~~~~~~~~~~~~~~
error: command '/home/editurn/openwrt/immortalwrt/staging_dir/host/bin/gcc' failed with exit code 1
````

### OpenWrt release

SNAPSHOT

### OpenWrt target/subtarget

rockchip/armv8

### Device

FriendlyElec NanoPi R2S

### Image kind

Self-built image

### Additional info

Upstream fix: https://github.com/u-boot/u-boot/commit/a63456b9191fae2fe49f4b121e025792022e3950

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by 1715173329** [comment]
I've created a PR for this: #17352
