### PR TITLE
tools/elfutils: remove dirname

### PR DESCRIPTION
**Pull request by robimarko**
In the 0.191 update dirname was used instead of <libgen.h> to fix the poisoned basename error:
```
/usr/include/libgen.h:35:9: error: attempt to use poisoned "basename"
       35 | #define basename        __xpg_basename
```

However, doing this has lead to libelf.a pulling in xmalloc, xstrdup and friends and statically linking them thus leading to a symbol name conflict with FRR host build and anything else that links against libelf and uses xmalloc and friends.

Well, it turns out that upstream has added a helper[1] for basename so it can compile with musl 1.2.5 which dropped the basename declaration, but it also means that we must NOT include <libgen.h> and that poisoned error is intentional and added to prevent duplicate basename definitions. This also means that for macOS we dont need to do any additional header inclusions as the new helper takes care of basename.

So, to fix the symbol conflict we can simply drop the <dirname.h> inclusion and build from elfutils.

Tested on Fedora 40 as well as macOS 14.4.1.

[1] https://sourceware.org/git/?p=elfutils.git;a=commit;h=a2194f6b305bf0d0b9dd49dccd0a5c21994c8eea

Fixes: #24030
Fixes: b6f025b42429 ("tools/elfutils: update to 1.91")

### CODE REVIEW

**Comment by trippleflux** [comment]
@robimarko & @httpstorm 
much obliged 👍 , thanks again.

**Comment by httpstorm** [comment]
@robimarko Well done! 🍻
Tested on Ubuntu 22.04.4 LTS and macOS 14.4.1 Intel.
I will now test the macOS [patch](https://github.com/openwrt/packages/issues/24030#issuecomment-2084879347) for `frr` you suggested and let you know how it goes.

Can you please review https://github.com/openwrt/packages/pull/24001 ? I haven't seen Rosen in the past few days. I made some changes there as he suggested.

**Comment by httpstorm** [comment]
@robimarko 
Tested your `frr` [fix](https://github.com/openwrt/packages/issues/24030#issuecomment-2084879347) on macOS and Ubuntu: solved too. Cheers Robi! 🍻 
[x64.2024-04-30.01-frr-macos.txt](https://httpstorm.com/share/.openwrt/test/2024-03-12_xcode-15.3/x64.2024-04-30.01-frr-macos.txt)
[x64.2024-04-30.02-frr-ubuntu.txt](https://httpstorm.com/share/.openwrt/test/2024-03-12_xcode-15.3/x64.2024-04-30.02-frr-ubuntu.txt)

**Comment by robimarko** [comment]
Its not mine, I just dug out this old PR:
https://github.com/FRRouting/frr/pull/6032

And manually updated the patch to apply

**Comment by httpstorm** [comment]
@robimarko 
I formatted the macOS section patch to meet the upstream requirements, and opened PR in OpenWRT and upstream. Please review and let me know if I should add signed off by you for refreshing the patch.
https://github.com/openwrt/packages/pull/24053
https://github.com/FRRouting/frr/pull/15890

**Comment by robimarko** [comment]
@httpstorm No need for my SoB, I just refreshed it to apply.

Thanks for pushing it upstream

**Comment by httpstorm** [comment]
@robimarko 
It was nice working together and learning.
