### PR TITLE
ltq-tapi: update to 4.18.1.0

### PR DESCRIPTION
**Pull request by neheb**
Allows reducing number of patches since some of them were upstreamed.

ping @abajk @DragonBluep 

I have no idea why this is available on the OpenWrt mirror but never updated.

### CODE REVIEW

**Comment by abajk** [comment]
I suspect that ltq-tapi is used by VoIP. My devices don't have FXS ports, so I have no chance to test this.

**Comment by neheb** [comment]
Hrm OK. I still wonder where this version came from and why it's on the openwrt sources page.

**Comment by hauke** [comment]
Yes this is the telephone API. It allows to use the analog phone ports in Asterisk. 

Please runtime test this.

**Comment by abajk** [comment]
@dangowrt @dhewg @sch-m @janh 
Don't remember which one of you had a working setup :)

**Comment by neheb** [comment]
I still have no idea where this comes from.

Google shows me https://dev.iopsys.eu/feed/intel/-/tree/release-5.3/ltq-voice-tapi?ref_type=heads

No idea how to interpret.

edit: found it: https://github.com/prplfoundation/feed-intel

**Comment by dangowrt** [comment]
I got a Lantiq VR9 box with FXS ports but currently no working analog phone to test. I'll try to get hold of one asap.
Meanwhile, maybe some of my @cosmiccableltd crew members, maybe @benibr could give it a shot on their hardware? Testing 6.18 would anyway be cool...

**Comment by neheb** [comment]
There seems to be a 4.19.1.0 that I can't find anywhere. Unfortunate.

**Comment by janh** [comment]
This might be the actual source (that is also where some of the DSL stuff comes from): https://gitlab.com/prpl-foundation/intel/ltq-voice-tapi

There also is a version 4.21.0.0.

**Comment by neheb** [comment]
Interesting.

So a bunch of lantiq packages come from UGW 8.5.2. That 4.21.0.0 version is the same. Unfortunately, I tried updating and couldn't get it to compile.

**Comment by sch-m** [comment]
Sorry, I cannot test this driver. We only have hardware without FXS ports (VRX268).

**Comment by hauke** [comment]
It could be that support for the VRX200 and Danube chip was removed from the more recent tapi versions.

**Comment by dangowrt** [comment]
I had to remove `package/kernel/lantiq/ltq-tapi/patches/510-linux-515.patch` which would no longer apply and looks like it is also no longer needed. Maybe.
Then I had to do some more patching to get it to build on Linux 6.18 due to changes of the timer API. Then it finally build.
However, it was all useless.
The Lantiq VMMC driver, which services the voice firmware running on the 2nd MIPS VPE on those Lantiq SoCs and acts as TAPI provider then fails to build because some datatypes don't match.
```
drv_vmmc_alm.c: In function 'VMMC_TAPI_LL_ALM_LEC_Set':
drv_vmmc_alm.c:2108:35: error: 'IFX_TAPI_LEC_NLP_OFF' undeclared (first use in this function); did you mean 'IFX_TAPI_WLEC_NLP_OFF'?
 2108 |       bEnNLP = (pLecConf->bNlp == IFX_TAPI_LEC_NLP_OFF) ?
      |                                   ^~~~~~~~~~~~~~~~~~~~
      |                                   IFX_TAPI_WLEC_NLP_OFF
drv_vmmc_alm.c:2108:35: note: each undeclared identifier is reported only once for each function it appears in
drv_vmmc_alm.c: In function 'VMMC_ALM_Func_Register':
drv_vmmc_alm.c:3118:28: error: assignment to 'IFX_int32_t (*)(IFX_TAPI_LL_CH_t *, const IFX_TAPI_TEST_LOOP_t *)' {aka 'int (*)(void *, const IFX_TAPI_TEST_LOOP_t *)'} from incompatible pointer type 'IFX_int32_t (*)(IFX_TAPI_LL_CH_t *, IFX_TAPI_TEST_LOOP_t *)' {aka 'int (*)(void *, IFX_TAPI_TEST_LOOP_t *)'} [-Wincompatible-pointer-types]
 3118 |    pAlm->TestLoop          = VMMC_TAPI_LL_ALM_VMMC_Test_Loop;
      |                            ^
drv_vmmc_alm.c:3130:23: error: assignment to 'IFX_int32_t (*)(IFX_TAPI_LL_CH_t *, const IFX_TAPI_GR909_START_t *)' {aka 'int (*)(void *, const IFX_TAPI_GR909_START_t *)'} from incompatible pointer type 'IFX_int32_t (*)(IFX_TAPI_LL_CH_t *, IFX_TAPI_GR909_START_t *)' {aka 'int (*)(void *, IFX_TAPI_GR909_START_t *)'} [-Wincompatible-pointer-types]
 3130 |    pAlm->GR909_Start  = VMMC_TAPI_LL_ALM_GR909_Start;
      |                       ^
drv_vmmc_alm.c:3142:24: error: assignment to 'IFX_int32_t (*)(IFX_TAPI_LL_CH_t *, const IFX_TAPI_FXO_FLASH_CFG_t *)' {aka 'int (*)(void *, const IFX_TAPI_FXO_FLASH_CFG_t *)'} from incompatible pointer type 'IFX_int32_t (*)(IFX_TAPI_LL_CH_t *, IFX_TAPI_FXO_FLASH_CFG_t *)' {aka 'int (*)(void *, IFX_TAPI_FXO_FLASH_CFG_t *)'} [-Wincompatible-pointer-types]
 3142 |    pAlm->FXO_FlashCfg  = VMMC_TAPI_LL_ALM_FxoFlashCfg;
      |                        ^
drv_vmmc_alm.c:3143:24: error: assignment to 'IFX_int32_t (*)(IFX_TAPI_LL_CH_t *, const IFX_TAPI_FXO_OSI_CFG_t *)' {aka 'int (*)(void *, const IFX_TAPI_FXO_OSI_CFG_t *)'} from incompatible pointer type 'IFX_int32_t (*)(IFX_TAPI_LL_CH_t *, IFX_TAPI_FXO_OSI_CFG_t *)' {aka 'int (*)(void *, IFX_TAPI_FXO_OSI_CFG_t *)'} [-Wincompatible-pointer-types]
 3143 |    pAlm->FXO_OsiCfg    = VMMC_TAPI_LL_ALM_FxoOsiCfg;
      |                        ^
drv_vmmc_alm.c:3145:26: error: assignment to 'IFX_int32_t (*)(IFX_TAPI_LL_CH_t *, const IFX_TAPI_FXO_LINE_MODE_t *)' {aka 'int (*)(void *, const IFX_TAPI_FXO_LINE_MODE_t *)'} from incompatible pointer type 'IFX_int32_t (*)(IFX_TAPI_LL_CH_t *, IFX_TAPI_FXO_LINE_MODE_t *)' {aka 'int (*)(void *, IFX_TAPI_FXO_LINE_MODE_t *)'} [-Wincompatible-pointer-types]
 3145 |    pAlm->FXO_LineModeSet = VMMC_TAPI_LL_ALM_FxoLineModeSet;
      |                          ^
```

This is the point I gave up.
Screenshot From 2026-05-15 02-18-19

This also tells a lot. New TAPI 4 was uploaded for VRX500, a SoC we don't even support...

**Comment by neheb** [comment]
hrm unfortunate.
