### PR TITLE
qualcommax: qca_ppe: fix per-port egress wedges

### PR DESCRIPTION
**Pull request by JuliusBairaktaris**
Four fixes for the same failure: a port stops transmitting with its carrier up, and nothing short of a reboot brings it back. They are sent together because they are one fault family in the PPE's egress path, they touch the same file, and the last one depends on the first.

* **gate switch-fabric TX-MAC across carrier flaps** — the fabric otherwise dequeues into a MAC that is still being re-clocked.
* **disable EEE** — an idle port enters low-power idle and egress handed to the waking MAC latches the same way.
* **give multicast queues idle DRR scheduler slots** — sharing a slot puts two queues on one DRR node, and when both cross empty->non-empty together the node's credit rotation latches.
* **drain a port's egress path when its link goes down** — packets left in the egress path when the link drops wedge the queue manager. This one needs the first commit's gate in place, which is why it is stacked here rather than sent separately.

The last commit follows Qualcomm's own driver, whose in-code comment states the mechanism directly: `/* release ppe port egress packets when link down */` (qca-ssdk `30c10e7f`, "enable and disable loopback for xgmac to fix qm stuck issue"). ssdk gates the fabric, waits 10ms, then touches the MAC, and on an XGMAC port pulses MAC loopback. Its loopback is gated on `PORT_XGMAC_TYPE`, which on IPQ8074 is ports 5 and 6 only, so the 10ms wait is what covers ports 1-4.

### Scope, honestly

This is not reproducible on a plain host datapath and I do not expect it to be: the fault needs a link to drop while that port's egress queue is deep, and on the host path the CPU rather than the port is the bottleneck, so the queue stays shallow and there is nothing to strand. The evidence comes from an IPQ8074 offloading in hardware, where forwarding happens inside the fabric at line rate and the queue does back up — a port found dead with one egress queue holding 252 packets whose count never moved, MAC MIB frozen at exactly zero, and the firmware's per-port discard counter climbing one-for-one with what was offered.

Reproducing it needs that depth: with the peer forced to 100M and over-rate UDP into it, the egress queue reaches ~268 packets. With the series applied the link was dropped 55 times with 82-268 packets queued, and the port's queue measured empty while the link was down every time.

Supersedes #24189 and #24252, which are folded in here.

### CODE REVIEW

**Review by openwrt-ai — COMMENTED** [review]
Reviewed 1 new commit; no new issues found.

---
_Generated by [Claude Code](https://claude.ai/code)_

**Comment by JuliusBairaktaris** [comment]
- **Line width:** the added comment lines are all ≤ 76 columns; checkpatch is clean, so no reflow.
- **enable/disable symmetry:** they pair on every reachable path. phylink only calls `mac_link_down`/`mac_link_up` with an interface from the port's `supported_interfaces`, and across a real flap both get the same interface — the disable in link-down and the final re-enable in link-up always match. The early-return paths named (the "invalid mode for port < 5" guard and the `default:` cases) are the driver's pre-existing defensive branches for interface/port combinations that don't occur on these boards (ports < 5 are the QCA8075 gigabit ports, never 2500BASEX/USXGMII/10GBASER). Even if one were somehow hit, leaving TX-MAC disabled for an interface whose MAC was never brought up is the correct fail-closed state — a port that didn't come up shouldn't forward — not a black-hole of a working port. Mirroring the guard into link-down would add defensive code for a branch that never executes, which I'd rather not do.

**Review by openwrt-ai — COMMENTED** [review]
Reviewed 1 new commit; no new issues found.

---
_Generated by [Claude Code](https://claude.ai/code)_

**Comment by JuliusBairaktaris** [comment]
This one, #24189 and #24252 now each carry an in-code rationale: what hardware misbehaviour the write prevents, on what event it fires, and why removing it re-opens the wedge. They read as one-line register pokes otherwise, and the reason belongs next to the code rather than only in the commit body — a later rebase onto new upstream is exactly when someone deletes a line like this.

No functional change in any of the three; comments only.

@Ansuel @robimarko — these have been open a couple of weeks. Any objection to the approach, or anything you would like reworked?

File: target/linux/qualcommax/files/drivers/net/ethernet/qualcomm/qca_ppe_main.c [hunk 1]
```diff
@@ -982,6 +982,19 @@ static void qca_ppe_mac_link_down(struct phylink_config *config,
...
+	 * Stop the switch fabric feeding this port before the MAC is torn
+	 * down, and turn it back on only after the MAC is up again (end of
+	 * qca_ppe_mac_link_up()). Left enabled across a flap, the fabric
+	 * dequeues into a MAC that is still being re-clocked and latches the
+	 * port's queue-manager egress scheduler in a state that never drains:
+	 * the link comes back at full speed and the host keeps queueing, but
+	 * nothing leaves the wire until the box is rebooted. The vendor ssdk
+	 * driver gates the same bit on every link change; both halves of this
+	 * are required.
+	 */
```
Comment (openwrt-ai) [inline target/linux/qualcommax/files/drivers/net/ethernet/qualcomm/qca_ppe_main.c]: nit: both new block comments open with a bare `/*` on its own line, which is the generic kernel style rather than the netdev style used by `drivers/net`. Text starts on the `/*` line there. The sibling file in this same directory already follows it — [`qca_ppe_scheduler.c:85-86`](``https://github.com/openwrt/openwrt/blob/295b349c097bd0c2fa0b3baeb070f43c2e828b99/target/linux/qualcommax/files/drivers/net/ethernet/qualcomm/qca_ppe_scheduler.c#L85-L86)`` — and in upstream `drivers/net/ethernet/qualcomm` the only bare-`/*` openers are the license headers. Since the stated intent is that this comment survives a future rebase onto upstream, matching netdev style now avoids a reflow later.

checkpatch won't catch it: the `NETWORKING_BLOCK_COMMENT_STYLE` check no longer exists in 6.12's `scripts/checkpatch.pl`, only the generic `BLOCK_COMMENT_STYLE` ones — so "checkpatch is clean" doesn't cover this.

```suggestion
	/* Stop the switch fabric feeding this port before the MAC is torn
	 * down, and turn it back on only after the MAC is up again (end of
	 * qca_ppe_mac_link_up()). Left enabled across a flap, the fabric
	 * dequeues into a MAC that is still being re-clocked and latches the
	 * port's queue-manager egress scheduler in a state that never drains:
	 * the link comes back at full speed and the host keeps queueing, but
	 * nothing leaves the wire until the box is rebooted. The vendor ssdk
	 * driver gates the same bit on every link change; both halves of this
	 * are required.
	 */
```

Same applies to the second comment at lines 1141-1144.

---
_Generated by [Claude Code](https://claude.ai/code)_

**Review by openwrt-ai — COMMENTED** [review]
Reviewed the changes since 79d5262 — the delta is comments-only, matching the description in the PR thread. The two register writes are byte-identical to the previously reviewed revision, and CI is green on 295b349 (qualcommax ipq50xx/ipq60xx/ipq807x kernel builds, patch check, formality checks all pass). One style nit inline.

---
_Generated by [Claude Code](https://claude.ai/code)_

File: target/linux/qualcommax/files/drivers/net/ethernet/qualcomm/qca_ppe_main.c [hunk 2]
```diff
@@ -1122,8 +1135,19 @@ static void qca_ppe_mac_link_up(struct phylink_config *config,
...
+
+	/*
+	 * Fabric TX-MAC comes back on only now that the MAC is up, and on
+	 * every exit path: the matching disable in qca_ppe_mac_link_down()
+	 * runs before that function looks at the interface at all, so an
+	 * early return here would leave the port with its carrier up, its
+	 * receive path working and its transmit path switched off in the
+	 * fabric - silently, since a gated fabric discards without counting.
+	 */
+out:
```
Comment (openwrt-ai) [inline target/linux/qualcommax/files/drivers/net/ethernet/qualcomm/qca_ppe_main.c]: On all three `goto out` paths the port's own MAC enables are still cleared, so "its receive path working" doesn't hold — and the state this leaves behind is the one the gate exists to prevent.

Concretely, for the reachable case (a port 1–4 brought up as 2500BASEX without inband):

- link-down runs [`ppe_port_gmac_set(priv, port, false, false)` at qca_ppe_main.c:1007](``https://github.com/openwrt/openwrt/blob/9b0478ddcb75646657fc99e83428cefca6c59958/target/linux/qualcommax/files/drivers/net/ethernet/qualcomm/qca_ppe_main.c#L1007),`` which clears **both** `PPE_MAC_ENABLE_TXMAC_EN` and `PPE_MAC_ENABLE_RXMAC_EN` — see [`ppe_port_gmac_set()`](``https://github.com/openwrt/openwrt/blob/9b0478ddcb75646657fc99e83428cefca6c59958/target/linux/qualcommax/files/drivers/net/ethernet/qualcomm/qca_ppe_main.c#L18-L34).``
- link-up then hits the `port < 5` guard and jumps straight here. The only code that re-asserts those two bits is [the final switch at lines 1120-1136](``https://github.com/openwrt/openwrt/blob/9b0478ddcb75646657fc99e83428cefca6c59958/target/linux/qualcommax/files/drivers/net/ethernet/qualcomm/qca_ppe_main.c#L1120-L1136),`` and every `goto out` bypasses it.

Result: fabric TX-MAC = 1 into a port MAC with `TXMAC_EN = 0` and `RXMAC_EN = 0`. That is the fabric dequeuing into a MAC that is not enabled — the exact condition the disable in `qca_ppe_mac_link_down()` is there to avoid — and RX is off as well, not "working". Same reasoning for the `default:` at line 1063; the one at line 1138 is unreachable regardless, since its case list is identical to the first switch at lines 1042-1062, which already `goto out`s on `default`.

Your earlier reasoning in the thread ("leaving TX-MAC disabled for an interface whose MAC was never brought up is the correct fail-closed state") matches what the registers actually do here. Was the reversal driven by a measurement on one of these paths, or by the assumption that the MAC is up by the time `out:` is reached? If you want to keep the unconditional enable, the comment (and the matching paragraph in the commit message) shouldn't claim the receive path is up on those exits — and it'd be worth saying why enabling the fabric into a disabled MAC is safe, since that's the premise the rest of the patch argues against.

---
_Generated by [Claude Code](https://claude.ai/code)_

**Review by openwrt-ai — COMMENTED** [review]
Reviewed the delta since 295b349: the three `return`s in `qca_ppe_mac_link_up()` became `goto out`, and the trailing comment was reworded to justify that. One issue with the new unconditional enable, inline.

## Commit checks

- 9b0478d "qualcommax: qca_ppe: gate switch-fabric TX-MAC across carrier flaps" — the paragraph added to justify the unconditional enable says an early return would make the port "keep its carrier and its receive path while its transmit path stays gated off in the fabric". On those paths `PPE_MAC_ENABLE_RXMAC_EN` is still cleared by `qca_ppe_mac_link_down()` and never re-asserted, so the receive path is not up either, and the port MAC's own `TXMAC_EN` is off too. The rest of the reasoning ("the window is over once the function returns") rests on that description. Details inline.

---
_Generated by [Claude Code](https://claude.ai/code)_

File: target/linux/qualcommax/files/drivers/net/ethernet/qualcomm/qca_ppe_main.c [hunk 3]
```diff
@@ -1122,15 +1173,51 @@ static void qca_ppe_mac_link_up(struct phylink_config *config,
...
+{
 }
 
 static const struct phylink_mac_ops qca_ppe_phylink_mac_ops = {
 	.mac_prepare	= qca_ppe_mac_prepare,
 	.mac_config	= qca_ppe_mac_config,
 	.mac_link_down	= qca_ppe_mac_link_down,
 	.mac_link_up	= qca_ppe_mac_link_up,
+	.mac_enable_tx_lpi	= qca_ppe_mac_enable_tx_lpi,
+	.mac_disable_tx_lpi	= qca_ppe_mac_disable_tx_lpi,
```
Comment (openwrt-ai) [inline target/linux/qualcommax/files/drivers/net/ethernet/qualcomm/qca_ppe_main.c:1210]: These two initializers break the build on 6.12, which is still the target's `KERNEL_PATCHVER` — [`target/linux/qualcommax/Makefile:11-12`](https://github.com/openwrt/openwrt/blob/83369ca112580e5da7d1d111e706e5efe246f68a/target/linux/qualcommax/Makefile#L11-L12) added `KERNEL_TESTING_PATCHVER:=6.18` but kept 6.12 as the default, and `files/` is compiled against both. `phylink_mac_ops` only gained `mac_enable_tx_lpi`/`mac_disable_tx_lpi` in 6.14; they are absent from 6.12's `include/linux/phylink.h`.

```
drivers/net/ethernet/qualcomm/qca_ppe_main.c:1220:10: error: 'const struct phylink_mac_ops' has no member named 'mac_disable_tx_lpi'
 1220 |         .mac_disable_tx_lpi     = qca_ppe_mac_disable_tx_lpi,
drivers/net/ethernet/qualcomm/qca_ppe_main.c:1220:35: error: excess elements in struct initializer [-Werror]
cc1: all warnings being treated as errors
make[10]: *** [scripts/Makefile.build:229: drivers/net/ethernet/qualcomm/qca_ppe_main.o] Error 1
```

Both `Build qualcommax/ipq807x` and `Build qualcommax/ipq60xx` fail identically on this head (ipq50xx passes only because it doesn't set `CONFIG_QCOM_80211AX_PPE`).

The commit message's precondition — "depends on the qualcommax 6.18 uplift (#24031) and should be merged after it lands" — is now satisfied, but the uplift landed as the *testing* kernel only, so it isn't sufficient. Gating the two ops and the two stub definitions on `LINUX_VERSION_CODE >= KERNEL_VERSION(6, 14, 0)` would mirror what [`qca_edma.c:1195`](``https://github.com/openwrt/openwrt/blob/83369ca112580e5da7d1d111e706e5efe246f68a/target/linux/qualcommax/files/drivers/net/ethernet/qualcomm/qca_edma.c#L1195)`` already does in this same directory for the same one-file-two-kernels problem.

---
_Generated by [Claude Code](https://claude.ai/code)_

File: target/linux/qualcommax/files/drivers/net/ethernet/qualcomm/qca_ppe_main.c [hunk 4]
```diff
@@ -974,6 +974,30 @@ static void qca_ppe_mac_config(struct phylink_config *config,
...
+static void ppe_port_xgmac_loopback_pulse(struct qca_ppe_priv *priv, int port)
+{
+	int xgmac = port - 5;
+
+	if (port < 5 || port >= priv->data->num_ports)
+		return;
+
+	regmap_set_bits(priv->regmap, PPE_XGMAC_RX_CONF(xgmac),
+			PPE_XGMAC_LOOPBACK);
+	mdelay(1);
```
Comment (openwrt-ai) [inline target/linux/qualcommax/files/drivers/net/ethernet/qualcomm/qca_ppe_main.c]: `mdelay()` busy-waits for a full millisecond and is reserved for atomic context (Documentation/timers/timers-howto.rst). This path is unambiguously sleepable: the only caller is `qca_ppe_mac_link_down()`, which itself calls `msleep(10)` a few lines below, and every other delay in this file sleeps (`msleep(150)` at line 972, `msleep(100)` at 1420/1530/1532). No reason to spin here.

```suggestion
	usleep_range(1000, 2000);
```

---
_Generated by [Claude Code](https://claude.ai/code)_

File: target/linux/qualcommax/files/drivers/net/ethernet/qualcomm/qca_ppe_main.c [hunk 5]
```diff
@@ -990,13 +1038,16 @@ static void qca_ppe_mac_link_down(struct phylink_config *config,
...
 			ppe_port_gmac_set(priv, port, false, false);
-		else
+		} else {
+			ppe_port_xgmac_loopback_pulse(priv, port);
 			ppe_port_xgmac_set(priv, port, false, false);
+		}
 		break;
 	case PHY_INTERFACE_MODE_10GBASER:
 	case PHY_INTERFACE_MODE_USXGMII:
+		ppe_port_xgmac_loopback_pulse(priv, port);
```
Comment (openwrt-ai) [inline target/linux/qualcommax/files/drivers/net/ethernet/qualcomm/qca_ppe_main.c:1050]: The pulse runs while the port's receive path is still live. `PPE_XGMAC_RX_ENABLE` is only cleared by the [`ppe_port_xgmac_set()`](``https://github.com/openwrt/openwrt/blob/4f8870978e4c1fe312dd175d67a3c28902735684/target/linux/qualcommax/files/drivers/net/ethernet/qualcomm/qca_ppe_main.c#L36-L50)`` call on the next line, and the earlier `ppe_port_bridge_txmac_set(priv, port, false)` gates only the fabric's egress *toward* the port, not ingress *from* it. XGMAC `LM` (BIT(10) of `MAC_Rx_Configuration`) loops the transmitter into the receiver, so for that millisecond every frame drained out of the egress queue is presented to the PPE as an ingress frame on this port — forwarded per FDB and source-MAC-learned onto the port that is going down, which would move the MACs of hosts behind other ports onto this one.

Is that accounted for, or should the port's RX MAC / ingress be shut off before the pulse rather than after? Asking rather than asserting, since I can't see ssdk's surrounding sequence — the commit message notes ssdk pulses later only because it never disables TX MAC on this path, but that leaves open whether ssdk's port is otherwise already quiesced when its pulse fires.

Same question applies to the 2500BASEX inband arm at line 1044.

---
_Generated by [Claude Code](https://claude.ai/code)_

File: target/linux/qualcommax/files/drivers/net/ethernet/qualcomm/qca_ppe_scheduler.c [hunk 6]
```diff
@@ -691,16 +691,30 @@ static void ppe_l0_scheduler_init(struct qca_ppe_priv *priv)
...
+				int slot = k ? p->ucast_count - counts[k] + j : j;
 				struct l0_cfg c = {
 					.queue = bases[k] + j,
 					.port = p->port,
-					.sp = p->sp_base + j / PPE_MAX_SP_PRI,
-					.cpri = j % PPE_MAX_SP_PRI,
-					.cdrr = p->cdrr_base + j,
-					.epri = j % PPE_MAX_SP_PRI,
-					.edrr = p->cdrr_base + j,
+					.sp = p->sp_base + slot / PPE_MAX_SP_PRI,
```
Comment (openwrt-ai) [inline target/linux/qualcommax/files/drivers/net/ethernet/qualcomm/qca_ppe_scheduler.c:707]: Moving the multicast queues from slots 0..mcast_count-1 to the top slots also moves them to a different L0 SP: with `slot` now 12-15 (or 15 for port 7), `p->sp_base + slot / PPE_MAX_SP_PRI` resolves to `sp_base + 1`, not `sp_base`. Those two SP ids are different L1 flow nodes with different strict priorities — [`l1_cfg` at qca_ppe_scheduler.c:576-577](``https://github.com/openwrt/openwrt/blob/4f8870978e4c1fe312dd175d67a3c28902735684/target/linux/qualcommax/files/drivers/net/ethernet/qualcomm/qca_ppe_scheduler.c#L576-L577)`` maps index 48 to port 4 / pri 0 / drr 20 and index 49 to port 4 / pri 1 / drr 21, and the same `sp_base`/`sp_base+1` pairing exists for every port.

So each port's multicast and flooding queues change L1 priority level as a side effect of this remap. The commit message's "the scheduler topology (no new SPs, no L1 changes) stays untouched" is true of the `l1_cfg` table but not of which L1 node the multicast traffic resolves to. Was the priority-level change intended, and is broadcast/ARP/ND still safe from starvation when the unicast queues still on `sp_base` are congested?

---
_Generated by [Claude Code](https://claude.ai/code)_

**Review by openwrt-ai — COMMENTED** [review]
Reviewed the three commits added since 9b0478d — ae32cd4, 65fc669 and 4f88709. 14199b9 is a pure rebase of the previously reviewed 9b0478d; its diff against the new base is byte-identical, so nothing re-raised there.

## Commit checks

- ae32cd4 "qualcommax: qca_ppe: disable EEE to prevent idle-port egress wedge" — the message names the 6.18 uplift (#24031) as the only blocker and says the change "should be merged after it lands". It has landed, but as `KERNEL_TESTING_PATCHVER:=6.18` with `KERNEL_PATCHVER` still 6.12, so the stated precondition is met while the change still does not compile on the default kernel. The ipq807x and ipq60xx kernel jobs are red on this head for exactly that reason. Details inline.
- 65fc669 "qualcommax: qca_ppe: give multicast queues idle DRR scheduler slots" — "the scheduler topology (no new SPs, no L1 changes) stays untouched" does not match the diff: the new slot numbers push the multicast queues onto `sp_base + 1`, which is a different L1 flow node with a different strict priority than `sp_base`. The `l1_cfg` table is untouched, but the L1 node the multicast traffic resolves to is not. Details inline.

---
_Generated by [Claude Code](https://claude.ai/code)_

File: target/linux/qualcommax/files/drivers/net/ethernet/qualcomm/qca_ppe_main.c [hunk 7]
```diff
@@ -1124,13 +1162,40 @@ static void qca_ppe_mac_link_up(struct phylink_config *config,
 	default:
 		return;
 	}
+
+	/* MAC is up, so the fabric may feed the port again. The early returns
+	 * above bring no MAC up, so they leave the gate closed on purpose.
+	 */
+	ppe_port_bridge_txmac_set(priv, port, true);
```
Comment (openwrt-ai) [inline target/linux/qualcommax/files/drivers/net/ethernet/qualcomm/qca_ppe_main.c:1182]: This is not the only place the gate is opened, so the invariant "the fabric only feeds the port once the MAC is up" does not hold across an admin down/up cycle.

`PPE_PORT_BRIDGE_CTRL_TXMAC_EN` is also set unconditionally by DSA's `.port_enable` callback — [`qca_ppe_port_enable()` at qca_ppe_main.c:511-518](``https://github.com/openwrt/openwrt/blob/3f4ec015c9ddf2f6689aa0c1cf8d97aafbc18ffc/target/linux/qualcommax/files/drivers/net/ethernet/qualcomm/qca_ppe_main.c#L511-L518),`` wired up at [line 1332](``https://github.com/openwrt/openwrt/blob/3f4ec015c9ddf2f6689aa0c1cf8d97aafbc18ffc/target/linux/qualcommax/files/drivers/net/ethernet/qualcomm/qca_ppe_main.c#L1332)`` — and [`dsa_port_enable_rt()`](https://github.com/gregkh/linux/blob/f89c296854b755a66657065c35b05406fc18264d/net/dsa/port.c#L213-L231) runs it *before* `phylink_start()`, with `BR_STATE_FORWARDING` set in between.

So `ip link set lanX down; ip link set lanX up` gives:

1. `phylink_stop()` → `qca_ppe_mac_link_down()`: gate off, 10 ms drain, `ppe_port_gmac_set(priv, port, false, false)`.
2. `.port_disable` → gate off (already off).
3. `.port_enable` → **gate on**, port MAC still disabled.
4. `dsa_port_set_state_now(FORWARDING)`.
5. `phylink_start()` → … → `qca_ppe_mac_link_up()`: `clk_set_rate()` on the port TX/RX clocks, then `ppe_port_gmac_set(priv, port, true, true)`, then the enable on this line.

Between 3 and 5 the fabric is forwarding into a port MAC that is disabled and about to be re-clocked — the window this patch describes as latching the QM egress scheduler. The carrier-flap path is now covered, but the admin path re-opens the gate ahead of the MAC.

Was that path considered? Dropping the `ppe_port_bridge_txmac_set(priv, port, true)` from `qca_ppe_port_enable()` and letting `qca_ppe_mac_link_up()` be the only thing that opens the gate would make the invariant hold for both, since `.port_enable` is always followed by `phylink_start()` on ports that have a phylink instance. The CPU port would need care there — it takes the `default:` return in both switches of `qca_ppe_mac_link_up()` (see the commit-checks note in the review body), so for port 0 the enable in `qca_ppe_setup()` / `.port_enable` is the only thing that ever sets the bit.

---
_Generated by [Claude Code](https://claude.ai/code)_

**Review by openwrt-ai — COMMENTED** [review]
Reviewed the delta since 4f88709 — all four commits were amended, no rebase (base is still 83369ca).

Everything raised last time is addressed: the `goto out` reverted to `return` so the early exits now leave the gate closed, `mdelay(1)` became `usleep_range(1000, 2000)`, the loopback pulse clears `PPE_XGMAC_RX_ENABLE` in the same `regmap_update_bits()` write, the LPI ops are gated on `LINUX_VERSION_CODE >= KERNEL_VERSION(6, 14, 0)` mirroring `qca_edma.c`, and the block comments moved to netdev style. Each commit message was updated to match. Spot-checks against the 6.18.39 tree hold up: `PPE_XGMAC_LOOPBACK` matches `XGMAC_CONFIG_LM BIT(10)` in `dwxgmac2.h` at the same `+0x4` offset, and `phylink_bringup_phy()`'s `} else if (pl->mac_supports_eee_ops) { phy_disable_eee(phy); }` branch is exactly the "MAC has the ops but wants EEE always disabled" path the EEE commit relies on; 6.12's `phylink.h` has neither op, so the gate is required. CI has nothing failed on this head (kernel builds still queued).

One inline question on the interaction between the new gating and DSA's `.port_enable`.

## Commit checks

- 94a64eb "qualcommax: qca_ppe: gate switch-fabric TX-MAC across carrier flaps" — "neither combination occurs on these boards" does not hold for the `default:` case of the first interface switch. Port 0 gets only `PHY_INTERFACE_MODE_INTERNAL` in [`qca_ppe_phylink_get_caps()`](``https://github.com/openwrt/openwrt/blob/3f4ec015c9ddf2f6689aa0c1cf8d97aafbc18ffc/target/linux/qualcommax/files/drivers/net/ethernet/qualcomm/qca_ppe_main.c#L742-L748),`` and every in-tree qualcommax board with a PPE switch node declares `phy-mode = "internal"` plus a `fixed-link` on `port@0` (e.g. [ipq8072-dl-wrx36.dts:242-251](https://github.com/openwrt/openwrt/blob/3f4ec015c9ddf2f6689aa0c1cf8d97aafbc18ffc/target/linux/qualcommax/dts/ipq8072-dl-wrx36.dts#L242-L251)), so phylink is registered for the CPU port and `INTERNAL` reaches that `default:` in normal operation. The consequence is that `qca_ppe_mac_link_down()` gates the CPU port's fabric TX-MAC off while `qca_ppe_mac_link_up()` never re-asserts it. No black-hole follows in practice — DSA only calls `phylink_stop()` on a CPU port from `dsa_port_teardown()`, and `qca_ppe_setup()` and `.port_enable` are what set the bit for port 0 — but the sentence covers a case that does occur, and the accompanying in-code comment ("the early returns above bring no MAC up") reads as if port 0 were not among them.

---
_Generated by [Claude Code](https://claude.ai/code)_

File: target/linux/qualcommax/files/drivers/net/ethernet/qualcomm/qca_ppe_main.c [hunk 8]
```diff
@@ -982,6 +1010,26 @@ static void qca_ppe_mac_link_down(struct phylink_config *config,
 	struct qca_ppe_priv *priv = ds_to_priv(dp->ds);
 	int port = dp->index;
 
+	/* The CPU port is INTERNAL: it falls through both switches below
+	 * without its MAC being touched, and qca_ppe_mac_link_up() would not
+	 * re-open its gate. Leave it alone.
+	 */
```
Comment (openwrt-ai) [inline target/linux/qualcommax/files/drivers/net/ethernet/qualcomm/qca_ppe_main.c]: nit: `qca_ppe_mac_link_down()` has a single `switch (interface)` below this point, not two — "both switches" only fits `qca_ppe_mac_link_up()`, which has three. Since the comment says "below", it reads as describing this function.

```suggestion
	/* The CPU port is INTERNAL: it falls through the switch below
	 * without its MAC being touched, and qca_ppe_mac_link_up() would not
	 * re-open its gate. Leave it alone.
	 */
```


---
_Generated by [Claude Code](https://claude.ai/code)_

**Review by openwrt-ai — COMMENTED** [review]
Reviewed the delta since 3f4ec01. All four commits were re-created on a new base (83369ca -> c9833b9), but only the first one changed content; the other three differ solely in trailer order (`Signed-off-by` moved after `Assisted-by`). Commit messages match their changes, so no commit-check section.

The previous finding is addressed, and the fix holds up on inspection:

- `qca_ppe_mac_link_down()` now returns early for the CPU port, so its fabric TX-MAC is no longer gated off by a path that never re-opens it. Port 0's gate stays owned by `qca_ppe_setup()` and `.port_enable`, as before this series.
- `.port_enable` now only opens the gate for the CPU port. `dsa_port_enable_rt()` calls `ds->ops->port_enable()` before `phylink_start()` ([port.c:217-236](https://github.com/gregkh/linux/blob/2eed76b0f3a94e0af5efce2f42a2bd6e4faa8e83/net/dsa/port.c#L217-L236), v6.12.100), so the commit message's ordering claim checks out, and `qca_ppe_mac_link_up()` becoming the sole opener for user ports is consistent with `qca_ppe_setup()` already clearing `PPE_PORT_BRIDGE_CTRL_TXMAC_EN` on every non-CPU port at probe.
- Checked the in-tree boards for a user port that would now never get its gate opened: `qca_ppe_phylink_get_caps()` advertises the RGMII modes on ports 1-4, and those fall into the `default: return` of `qca_ppe_mac_link_up()`'s first switch — but no qualcommax board puts an RGMII phy-mode on a PPE port (the only `rgmii-rxid` in `target/linux/qualcommax/dts/` is on the cascaded QCA8337 in `ipq8074-rt-ax89x.dts`, whose PPE-side port is QSGMII). Every `&switch` user port in-tree resolves to a case that opens the gate. The `ipq5018` boards with a `&switch` node use the QCA8337, not the PPE, so the "every board with a PPE switch node gives port@0 a fixed-link" claim holds too.

CI is green on this head (ipq50xx/ipq60xx/ipq807x kernel builds, patch check, formality checks).

One comment-wording nit inline.

---
_Generated by [Claude Code](https://claude.ai/code)_

**Review by openwrt-ai — COMMENTED** [review]
Reviewed the delta since e16e255. All four commits were amended, but the tree change is a single line: the `qca_ppe_mac_link_down()` comment now says "falls through the switch below" instead of "both switches", which is the previous nit applied — the function has one `switch (interface)`. The other three commits are byte-identical in content and message; the base is unchanged (ce16dd8). CI is green on this head (ipq50xx/ipq60xx/ipq807x kernel builds, kernel patch check, formality checks).

No new issues found.

---
_Generated by [Claude Code](https://claude.ai/code)_

**Comment by robimarko** [comment]
Thanks! Rebased on top of main and merged!
