### PR TITLE
libevent2: Make it build using OpenSSL 1.1.0

### PR DESCRIPTION
**Pull request by cotequeiroz**
This is a backport of @kroeckx patch upstream that was merged in libevent release-2.1.7-rc.

Signed-off-by: Eneas U de Queiroz <cote2004-github@yahoo.com>

### CODE REVIEW

**Comment by neheb** [comment]
Seems to be broken with deprecated APIs: 

le-proxy.o: In function `main':
le-proxy.c:(.text.startup+0x244): undefined reference to `SSL_library_init'
le-proxy.c:(.text.startup+0x248): undefined reference to `SSL_library_init'
le-proxy.c:(.text.startup+0x254): undefined reference to `ERR_load_crypto_strings'
le-proxy.c:(.text.startup+0x258): undefined reference to `ERR_load_crypto_strings'
le-proxy.c:(.text.startup+0x264): undefined reference to `SSL_load_error_strings'
le-proxy.c:(.text.startup+0x268): undefined reference to `SSL_load_error_strings'
le-proxy.c:(.text.startup+0x274): undefined reference to `OpenSSL_add_all_algorithms'
le-proxy.c:(.text.startup+0x278): undefined reference to `OpenSSL_add_all_algorithms'

Mind you this is after an rm -rf of the build directory.

**Comment by cotequeiroz** [comment]
These were sample/test files that are not installed in openwrt.  How about we reduce build time by skipping them?  It would be really easy to correct them as well, but not calling these functions when openssl > 1.1.0--they're all unnecessary with the new version.

**Comment by neheb** [comment]
ACK

**Comment by cotequeiroz** [comment]
@jow- 
Have you looked at this?
@diizzyy, you advised me not to upgrade to 2.1.8 earlier.  Do you have any issue with this PR?
I'm getting closer to have all of the packages compatible with openssl 1.1.0.  I know this is not a straightforward patch, but it is a rebase of an upstream commit, and it is not that hard to audit.
By the way, I've just added another commit from upstream related to openssl-1.1.
Cheers,

**Comment by diizzyy** [comment]
2.1.8 is broken when it comes to linking/dependencies regarding SSL and to my knowledge there isn't a need to follow Master/HEAD/trunk or at least no one has been able to make show the benefits.

**Comment by cotequeiroz** [comment]
Thanks for replying. When I asked about the PR, I meant the current PR, which does not upgrade, and does not change any linking/dependencies. My main goal is to update OpenSSL without breaking any packages. From what I can tell, it is working properly, but I would like someone to confirm this, or to point out any shortcomings or objections, of course. The reason I mention this is a patch from upstream is because I imagine more people have tested it. This is not just a blind cherry-pick. 
Cheers

**Comment by cotequeiroz** [comment]
I'm closing this as the package was upgraded to v. 1.2.8, which is compatible with openssl 1.1.
