### PR TITLE
meson: new target for amlogic S805 and S9 SoCs

### PR DESCRIPTION
**Pull request by ChalesYu**
Hi ,   This may be looks like an RFC . These amlogic SoCs released at 2017 and have more than 5 years old.
For now , these board has been supported by some repo:
https://github.com/ophub/amlogic-s9xxx-openwrt
https://github.com/hyphop/khadas-openwrt
But master branch still didn't support that, so want to add it.

These is based on Stijn Tintel  tree on:
https://git.openwrt.org/?p=openwrt/staging/stintel.git;a=shortlog;h=refs/heads/meson
https://patchwork.ozlabs.org/project/openwrt/cover/20181019173707.22951-1-stijn@linux-ipv6.be/

Boot progress:
For S805 , Armbian is used to support that board. mainline uboot didn't support yet. Can only use vendor uboot shell to load mainline uboot and dtb  from SD/USB to boot.
For S905 , mainline uboot is supported and can use `go` command to load from vendor uboot , then do boot progress.

For more information , see
https://linux-meson.com/howto.html

Tested on :
meson8b S805 Odroid C1 variant board
mesongx GXBB S905(M) Odroid C1 variant board
mesongx GXL S905X/L Khadas VIM 1

But I guess this code style also need some change, need peoples suggestion.
And , Of course , these commits looks not ready , will fix it by git `force-push` .

### CODE REVIEW

**Comment by predators46** [comment]
Ping @stintel

**Comment by stintel** [comment]
There is a reason there are multiple commits in my tree. Please follow https://openwrt.org/submitting-patches#creating_and_sending_your_change. I would suggest you start from my tree and make your changes on top. Pay special attention to point 3 in the above link. This PR right now is unreviewable.

**Comment by stintel** [comment]
Thanks. I'm currently travelling, will try to review this when I'm back home next week. Did you not have trouble booting 5.10? I have the 5.10 bump in a local branch, with a remark that it doesn't boot. Tested on Odroid C2. I also have a VIM3 and a VIM3L, so we can have a nice set of supported boards once this is ready to go in master.

**Comment by predators46** [comment]
i get an error while creating

```Target System (Amlogic Meson family)  --->
Subtarget (Amlogic S9 SoC family (64 bit))  --->
Target Profile (S905X Design Reference Board)  --->```

```make -C /home/open/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-meson_mesongx/linux-5.10.134 KCFLAGS="-fmacro-prefix-map=/home/open/openwrt/build_dir/target-aarch64_cortex-a53_musl=target-aarch64_cortex-a53_musl -fno-caller-saves " HOSTCFLAGS="-O2 -I/home/open/openwrt/staging_dir/host/include  -Wall -Wmissing-prototypes -Wstrict-prototypes" CROSS_COMPILE="aarch64-openwrt-linux-musl-" ARCH="arm64" KBUILD_HAVE_NLS=no KBUILD_BUILD_USER="" KBUILD_BUILD_HOST="" KBUILD_BUILD_TIMESTAMP="Fri Aug  5 16:31:24 2022" KBUILD_BUILD_VERSION="0" KBUILD_HOSTLDFLAGS="-L/home/open/openwrt/staging_dir/host/lib" CONFIG_SHELL="bash" V=''  cmd_syscalls=  KERNELRELEASE=5.10.134 CC="aarch64-openwrt-linux-musl-gcc" Image dtbs modules                                                        make[5]: Entering directory '/home/open/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-meson_mesongx/linux-5.10.134'                                                    HOSTCC  scripts/extract-cert                                                         /usr/bin/ld: /home/open/openwrt/staging_dir/host/lib/libcrypto.a(libcrypto_la-eng_all.o): in function `ENGINE_load_builtin_engines':                                          eng_all.c:(.text+0x30): undefined reference to `pthread_once'                          /usr/bin/ld: /home/open/openwrt/staging_dir/host/lib/libcrypto.a(libcrypto_la-err.o): in function `ERR_load_ERR_strings':                                                     err.c:(.text+0xb7e): undefined reference to `pthread_once'                             /usr/bin/ld: /home/open/openwrt/staging_dir/host/lib/libcrypto.a(libcrypto_la-err_all.o): in function `ERR_load_crypto_strings':                                              err_all.c:(.text+0xaf): undefined reference to `pthread_once'                          /usr/bin/ld: /home/open/openwrt/staging_dir/host/lib/libcrypto.a(libcrypto_la-c_all.o): in function `OpenSSL_add_all_ciphers':                                                c_all.c:(.text+0x96f): undefined reference to `pthread_once'                           /usr/bin/ld: /home/open/openwrt/staging_dir/host/lib/libcrypto.a(libcrypto_la-c_all.o): in function `OpenSSL_add_all_digests':                                                c_all.c:(.text+0x98f): undefined reference to `pthread_once'                           /usr/bin/ld: /home/open/openwrt/staging_dir/host/lib/libcrypto.a(libcrypto_la-crypto_init.o):crypto_init.c:(.text+0x51): more undefined references to `pthread_once' follow   collect2: error: ld returned 1 exit status                                             make[6]: *** [scripts/Makefile.host:95: scripts/extract-cert] Error 1                  make[5]: *** [Makefile:1208: scripts] Error 2                                          make[5]: Leaving directory '/home/open/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-meson_mesongx/linux-5.10.134'                                                   make[4]: *** [Makefile:33: /home/open/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-meson_mesongx/linux-5.10.134/.modules] Error 2                                   make[4]: Leaving directory '/home/open/openwrt/target/linux/meson'                     make[3]: *** [Makefile:11: compile] Error 2                                            make[3]: Leaving directory '/home/open/openwrt/target/linux'                           time: target/linux/compile#0.81#0.19#0.98                                                  ERROR: target/linux failed to build.                                               make[2]: *** [target/Makefile:30: target/linux/compile] Error 1                        make[2]: Leaving directory '/home/open/openwrt'                                        make[1]: *** [target/Makefile:23: /home/open/openwrt/staging_dir/target-aarch64_cortex-a53_musl/stamp/.target_compile] Error 2                                                make[1]: Leaving directory '/home/open/openwrt'                                        make: *** [/home/open/openwrt/include/toplevel.mk:230: world] Error 2```

**Comment by xabolcs** [comment]
> - forget mainline uboot ...

For Odroid N2 the mainline U-Boot is far better than the BSP version, and it's more conpatible with the mainline kernel. (See the [few comments](https://forum.odroid.com/viewtopic.php?p=350493#p350493) on odroid's forum!)

If there is support for any of these board in mainline U-Boot, then it should be used for that board, IMHO.

**Comment by ChalesYu** [comment]
This PR is only talk about `mesongx` and `meson8b` ,  Odroid N2 and VIM3 is `mesong12a/b` `mesonsm`  , so seems a little off-topic. 
These new board have enough performance so using armbian kernel looks like a better choice.

>  Did you not have trouble booting 5.10? I have the 5.10 bump in a local branch, with a remark that it doesn't boot. Tested on Odroid C2.

Odroid C2 is a GXBB board, I remember it need to update latest mainline u-boot to boot kernel 5.10. But using BSP uboot didn't have that issue , tested on a S905X(GXL) board.

>make[6]: *** [scripts/Makefile.host:95: scripts/extract-cert] Error 1 

looks like your build host environment have some issue, This PR may meed to fix(add) something to kernel config , but won't have this kind of error.

> For S805 , Armbian is used to support that board. mainline uboot didn't support yet. Can only use vendor uboot shell to load mainline <del> uboot </del> kernel and dtb from SD/USB to boot.

I have write something wrong , `meson8b` didn't support mainline u-boot (yet), but it can boot kernel 5.10/5.15 using vendor BSP u-boot. And this is why I keep these target didn't using mainline u-boot.

Maybe some day mainline u-boot works good, other people can add some code to build and switch to that. But I won't write that code.

**Comment by ChalesYu** [comment]
> If there is support for any of these board in mainline U-Boot, then it should be used for that board, IMHO.

If user really want use mainline u-boot , they can do this manually by themselves.

The boot progress may finally like @LibreELEC did , If someone want to write compile step code ,can ask suggestion from @chewitt.
And, looks like GXBB board still have some issue  https://github.com/LibreELEC/amlogic-boot-fip/pull/8
some prebuilt u-boot blob: https://chewitt.libreelec.tv/testing/

**Comment by chewitt** [comment]
I wouldn't personally seek to support Meson8 hardware. Upstream kernel support is incomplete and while MartinB's linux branches are better (due to lots of not-yet-upstream patches) there is no upstream u-boot support (not likely to change anytime soon or ever) and the boards are old and few people have them.

GXBB/GXL/GXM and newer G12A/G12B/SM1 devices have good core OS support except for media codec things (not sure if that's important to OpenWRT). Upstream u-boot works well on boards/devices that have support and https://github.com/LibreELEC/amlogic-boot-fip has all the FIP sources you'd need to create single .img files that can SD/eMMC boot the boards. The repo is deliberately structured to suit distro build-systems and .img packaging; LE/Armbian both use it.

I would advocate using recent kernels not ancient LTS releases because fewer people are testing the backports that drip-feed into them and recent kernels generally have more things fixed/added. Amlogic doesn't have much community support in the form of board/driver development, but there is slow feed of improvements.

I would avoid supporting TV boxes except for the few that have FIPs and upstream u-boot support, because everything else uses cheap parts and low-bin RAM and you're dependent on vendor u-boot, which works but complicates distro packaging with the bootscript garbage needed for hooking vendor u-boot. I would also avoid the generic reference design boards, as while they often work it mostly attracts people with TV boxes that can't tell their arse from elbow who don't figure out boot requirements and are a drain on support efforts. Focus on the SBC devices.

**Comment by 0x5e** [comment]
I have M401A with s905l3a running armbian, if there's anything I can help, please contact me :)

**Comment by stintel** [comment]
> If user really want use mainline u-boot , they can do this manually by themselves.

To be frank, I think you got it backwards. We shall use mainline u-boot and if the user really wants to use some broken vendor fork they can do it themselves.

**Comment by stintel** [comment]
> GXBB/GXL/GXM and newer G12A/G12B/SM1 devices have good core OS support except for media codec things (not sure if that's important to OpenWRT).

I'd say no. As much as I'd like to run Kodi (or Jellyfin maybe) on OpenWrt, for those purposes people can use *ELEC.

> I would advocate using recent kernels not ancient LTS releases

OpenWrt is based on LTS releases, 22.03 uses 5.10, master is evolving to 5.15 so I suggest we focus on 5.15. Should be recent enough to support many boards.

@chewitt thank you for your insights.

**Comment by ChalesYu** [comment]
> To be frank, I think you got it backwards. We shall use mainline u-boot and if the user really wants to use some broken vendor fork they can do it themselves.

No, not backwards. I still suggest focus on compatibility , both vendor and mainline u-boot should able to boot (If vendor don't want support this ,they have burned eFUSE ,some GXM board did that already) . For mainline u-boot, add a simpile boot.scr is enough.

And yes, the next step may fix configs for kernel 5.15 (or more newer).

**Comment by predators46** [comment]
I have a TBee-Box device this is amlogic s905x can this be added? I see it can run openwrt using armbian kernel

https://github.com/ophub/amlogic-s9xxx-openwrt/releases/download/OpenWrt_Aml_official_09.06.0730/openwrt_s905x_k5.10.141_2022.09.06.img.gz

**Comment by openwrtfirmwarecostum** [comment]
i am trying to build on openwrt 22.03.0 

i added meson patch 

I'm using ubuntu 20.04 LTS 

when i build meson on openwrt 22.03.0 i get warning and error while building it here I will attach those warnings and errors here. 

although i know this is for openwrt master branch


1. Error

i saw this on the openwrt forum and solved this error. I don't know what's wrong

https://forum.openwrt.org/t/undefined-reference-to-pthread-once/65789/3

```gcc -Wp,-MD,scripts/.extract-cert.d -Wall -Wmissing-prototypes -Wstrict-prototypes -O2 -fomit-frame-pointer -std=gnu89  -O2 -I/usr/src/openwrt/staging_dir/host/include  -Wall -Wmissing-prototypes -Wstrict-prototypes   -I/usr/src/openwrt/staging_dir/host/include -I./tools/include    -o scripts/extract-cert scripts/extract-cert.c -L/usr/src/openwrt/staging_dir/host/lib -lcrypto
/usr/bin/ld: /usr/src/openwrt/staging_dir/host/lib/libcrypto.a(libcrypto_la-eng_all.o): in function `ENGINE_load_builtin_engines':
eng_all.c:(.text+0x30): undefined reference to `pthread_once'
/usr/bin/ld: /usr/src/openwrt/staging_dir/host/lib/libcrypto.a(libcrypto_la-err.o): in function `ERR_load_ERR_strings':
err.c:(.text+0xd2e): undefined reference to `pthread_once'
/usr/bin/ld: /usr/src/openwrt/staging_dir/host/lib/libcrypto.a(libcrypto_la-err_all.o): in function `ERR_load_crypto_strings':
err_all.c:(.text+0x9f): undefined reference to `pthread_once'
/usr/bin/ld: /usr/src/openwrt/staging_dir/host/lib/libcrypto.a(libcrypto_la-c_all.o): in function `OpenSSL_add_all_ciphers':
c_all.c:(.text+0x9df): undefined reference to `pthread_once'
/usr/bin/ld: /usr/src/openwrt/staging_dir/host/lib/libcrypto.a(libcrypto_la-c_all.o): in function `OpenSSL_add_all_digests':
c_all.c:(.text+0x9ff): undefined reference to `pthread_once'
/usr/bin/ld: /usr/src/openwrt/staging_dir/host/lib/libcrypto.a(libcrypto_la-crypto_init.o):crypto_init.c:(.text+0x51): more undefined references to `pthread_once' follow
collect2: error: ld returned 1 exit status```


2.Error /warning

it seems that in config-5.10 something is missing, I set it like below. whether it's right or wrong

```Amlogic AIU (SND_MESON_AIU) [N/m/?] (NEW) n                                            
Amlogic AXG Playback FIFO support (SND_MESON_AXG_FRDDR) [N/m/?] (NEW) n                
Amlogic AXG Capture FIFO support (SND_MESON_AXG_TODDR) [N/m/?] (NEW) n                 
Amlogic AXG TDM Input Support (SND_MESON_AXG_TDMIN) [N/m/?] (NEW) n                    
Amlogic AXG TDM Output Support (SND_MESON_AXG_TDMOUT) [N/m/?] (NEW) n                  
Amlogic AXG Sound Card Support (SND_MESON_AXG_SOUND_CARD) [N/m/?] (NEW) n              
Amlogic AXG SPDIF Output Support (SND_MESON_AXG_SPDIFOUT) [N/m/?] (NEW) n              
Amlogic AXG SPDIF Input Support (SND_MESON_AXG_SPDIFIN) [N/m/?] (NEW) n                
Amlogic AXG PDM Input Support (SND_MESON_AXG_PDM) [N/m/?] (NEW) n                      
Amlogic GX Sound Card Support (SND_MESON_GX_SOUND_CARD) [N/m/?] (NEW) n                
Amlogic G12A To Internal DAC Control Support (SND_MESON_G12A_TOACODEC) [N/m/?] (NEW) n 
Amlogic G12A To HDMI TX Control Support (SND_MESON_G12A_TOHDMITX) [N/m/?] (NEW) n      
Amlogic T9015 DAC (SND_SOC_MESON_T9015) [N/m/?] (NEW) n```

3. warning

and lastly i got a warning error and it didn't stop the build

```musl-ld: warning: orphan section `__ksymtab_strings' from `arch/arm64/lib/memcmp.o' being placed in section `__ksymtab_strings'                         
aarch64-openwrt-linux-musl-ld: warning: orphan section `__ksymtab_strings' from `arch/arm64/lib/memcpy.o' being placed in section `__ksymtab_strings'                         
aarch64-openwrt-linux-musl-ld: warning: orphan section `__ksymtab_strings' from `arch/arm64/lib/memmove.o' being placed in section `__ksymtab_strings'                        
aarch64-openwrt-linux-musl-ld: warning: orphan section `__ksymtab_strings' from `arch/arm64/lib/memset.o' being placed in section `__ksymtab_strings'                         
aarch64-openwrt-linux-musl-ld: warning: orphan section `__ksymtab_strings' from `arch/arm64/lib/strchr.o' being placed in section `__ksymtab_strings'                         
aarch64-openwrt-linux-musl-ld: warning: orphan section `__ksymtab_strings' from `arch/arm64/lib/strcmp.o' being placed in section `__ksymtab_strings'                         
aarch64-openwrt-linux-musl-ld: warning: orphan section `__ksymtab_strings' from `arch/arm64/lib/strlen.o' being placed in section `__ksymtab_strings'                         
aarch64-openwrt-linux-musl-ld: warning: orphan section `__ksymtab_strings' from `arch/arm64/lib/strncmp.o' being placed in sectio```


and finally i finished it. I haven't tried burning on the memory card, I don't have an odroid and khadas vim1 device for me to test. if anyone wants to try please download here

https://github.com/openwrtfirmwarecostum/amlogic/tree/main/targets/meson/cortexa53

**Comment by cloudomate** [comment]
i have amlogic s905x3 based tv box which i think is SM1 family, S9 gen 3, currently have deployed ophub's port of openwrt which is build on armbian kernel for trial, i looking at their kernel compile script it appears they are downloading the kernel source from a unknown repo with no proper tracking and license, they claimed to have cloned @chewitt  repo, why not fork it instead ? They claim that openwrt community despises these TV boxes, i dont agree with that. Would love to contribute to support in anyway @ChalesYu, these are some really cheap and powerful devices,  1GE router/firewall less than  $70

**Comment by openwrtfirmwarecustom** [comment]
@cloudomate 

https://github.com/ophub/amlogic-s9xxx-openwrt/issues/374

**Comment by cloudomate** [comment]
> @cloudomate
> 
> [ophub/amlogic-s9xxx-openwrt#374](https://github.com/ophub/amlogic-s9xxx-openwrt/issues/374)
Thanks i had gone through this exchange, i really don't understand the rationale, for one to start their own derivative of product, ideally if they really want to help, they can contribute to  armbian and openwrt. 

1.  They are using armbian approach to build a new kernel and deploy application from armbain's repo, so with same kernel and modules they merge the rootfs build from openwrt's armvirt64 traget even the luci-app is a custom. 
2. The kernel compile script uses kernel  source which is claimed to be clone from chweitt, i ran a diff between two repos on my local machine, found lot of patching at kernel core modules 

See i am neither a expert developer nor a have good idea about kernel development cannot review the code for backdoors, trust is a important factor.   

Since this pull request was in stalled state, all I want to understand the exchange in this pull request i think what i understand is 1. mesongx, mesonsm1 etc should be treated as separate platform as ARM CPU micro-architecture is different. 
2. @stintel suggested waiting for kernel 5.15 support 
3. the reviews were not started, 6 reviews are required 

Will try to go though the pull request and see if i can replicate the same for mesonsm1 platform

**Comment by predators46** [comment]
there are already a lot of devices that are here

https://github.com/ophub/amlogic-s9xxx-openwrt/releases/tag/OpenWrt_official_save_2023.06

**Comment by ChalesYu** [comment]
Most S905X board (even TVBox) have enough hardware resource(1g memory and 4g emmc), it's good to go with ophub openwrt.

With a more stripped kernel config, compile, flash and run OpenWRT on a SPI flash is possible and amazing.
Although it is a challenge thing, but I believe ophub always can NOT flash into a 128M sdcard , flash into a 16M SPI flash is more impossible.

So On Hardware part:
On S905X board, it's possible to add a SOP-8 16M SPI flash on Hardware, but it will conflict with eMMC(just on software part).
(On S905X datasheet , pin BOOT_15 share function between emmc and spi flash),I have did this hardware MOD successfully on a S905X TVBox Board.
A development board name Libre Aml-S805X-AC have a 16M flash , looks like someone already did that(even with software part).

On software part:
like other router,boot progress is:
 1: u-boot boot from emmc , load and run a compressed kernel.
 2: kernel boot and mount a squashfs rootfs on SPI flash.
 3: same boot progress like other router.

of course, this is just my imagination, write enough code to make this come true need lot's of time. 

At least , I need to focus on maintain my basic life first , spend time on this is a more challenge thing for me.

BTW, I don't have S905X3 board , and won't buy and test these new board.

**Comment by tidurberdiri** [comment]
Pointing for the new meson target #24865

File: target/linux/meson/image/Makefile [hunk 1]
```diff
@@ -0,0 +1,176 @@
...
+endif
+
+define Device/odroid-c2
+  DEVICE_DTS := amlogic/meson-gxbb-odroidc2
+  DEVICE_PACKAGES +=
+  DEVICE_TITLE := ODROID C2
+endef
+ifeq ($(SUBTARGET),cortexa53)
+  TARGET_DEVICES += odroid-c2
+endif
```
Comment (openwrt-ai) [inline target/linux/meson/image/Makefile:109]: The device node names don't follow the `<vendor>_<model>` convention, which breaks sysupgrade here. With `REQUIRE_IMAGE_METADATA=1` (set in `platform.sh`), `SUPPORTED_DEVICES` defaults to `$(subst _,$(comma),$(1))` (include/image.mk:551). For a device named `odroid-c2` that resolves to `SUPPORTED_DEVICES = odroid-c2`, but the running `board_name` is `hardkernel,odroid-c2` — the exact string `platform.sh` matches on. The two won't match, so the metadata check rejects the image on upgrade. Naming the device `hardkernel_odroid-c2` makes `SUPPORTED_DEVICES` resolve to `hardkernel,odroid-c2` and fixes it.

Also, `DEVICE_TITLE` is the deprecated form (only 4 targets still use it, vs 115 using `DEVICE_VENDOR`); the current idiom is `DEVICE_VENDOR`/`DEVICE_MODEL`. And the empty `DEVICE_PACKAGES +=` line is a no-op that can be dropped.

```suggestion
define Device/hardkernel_odroid-c2
  DEVICE_DTS := amlogic/meson-gxbb-odroidc2
  DEVICE_VENDOR := Hardkernel
  DEVICE_MODEL := ODROID-C2
endef
ifeq ($(SUBTARGET),cortexa53)
  TARGET_DEVICES += hardkernel_odroid-c2
endif
```

The same rename applies to every other device block (`odroid-c1` -> `hardkernel_odroid-c1`, etc.); note `platform.sh`'s `case "$(board_name)"` already keys on `hardkernel,odroid-c2`, confirming the expected form.

---
_Generated by [Claude Code](https://claude.ai/code)_

File: target/linux/meson/image/uEnv.ini [hunk 2]
```diff
@@ -0,0 +1,3 @@
+dtb_name=dtb
+bootargs_mmc=root=/dev/mmcblk0p2  rootwait ro rootfstype=ext4,squashfs console=tty0, console=ttyAML0,115200 net.ifnames=0
```
Comment (openwrt-ai) [inline target/linux/meson/image/uEnv.ini:2]: Stray trailing comma after `console=tty0` — `console=tty0,` is a malformed console argument (comma with no baud/options). The `bootargs_usb` line just below correctly uses `console=tty0 console=ttyAML0,115200`. Drop the comma.

```suggestion
bootargs_mmc=root=/dev/mmcblk0p2  rootwait ro rootfstype=ext4,squashfs console=tty0 console=ttyAML0,115200 net.ifnames=0
```

---
_Generated by [Claude Code](https://claude.ai/code)_

**Review by openwrt-ai — COMMENTED** [review]
Reviewed 8 commits (fresh review). Commit messages all match their diffs. Two inline issues noted: device-node naming vs. `SUPPORTED_DEVICES`/`board_name` matching under `REQUIRE_IMAGE_METADATA=1`, and a stray comma in a `console=` bootarg. This is flagged by the author as an RFC/WIP that will be force-pushed, so treat these as directional.

---
_Generated by [Claude Code](https://claude.ai/code)_
