### PR TITLE
Fix kernel 6.18 build on macOS hosts

### PR DESCRIPTION
**Pull request by markmentovai**
I’m adding these patches to hack-6.18 without the expectation of upstreaming them, because I don’t expect that the upstream is sympathetic to cross builds, largely because these are very obvious portability issues that would have been discovered and fixed fairly quickly after the non-portable changes landed. In addition, it follows the pattern of [200-tools_portability.patch](https://github.com/openwrt/openwrt/blob/31f7baacf5192a3574b815a648b474b7244e9ccb/target/linux/generic/hack-6.18/200-tools_portability.patch), which is a non-upstreamed “hack” patch.

This fixes the `objtool` cross build:

```
  CC      …/linux-6.18.33/tools/objtool/builtin-check.o
builtin-check.c:13:10: fatal error: 'sys/sendfile.h' file
      not found
   13 | #include <sys/sendfile.h>
      |          ^~~~~~~~~~~~~~~~
1 error generated.
gmake[8]: *** […/linux-6.18.33/tools/build/Makefile.build:86: …/linux-6.18.33/tools/objtool/builtin-check.o] Error 1
```

It also fixes the `gen_init_cpio` cross build:

```
  HOSTCC  usr/gen_init_cpio
usr/gen_init_cpio.c:460:16: error: call to undeclared
      function 'copy_file_range'; ISO C99 and later do not support implicit
      function declarations [-Wimplicit-function-declaration]
  460 |                         this_read = copy_file_range(file, NULL, outfd, N...
      |                                     ^
usr/gen_init_cpio.c:677:31: error: use of undeclared
      identifier 'O_LARGEFILE'
  677 |                                      O_WRONLY | O_CREAT | O_LARGEFILE | O_TRUNC,
      |                                                           ^~~~~~~~~~~
2 errors generated.
gmake[7]: *** [scripts/Makefile.host:114: usr/gen_init_cpio] Error 1
```

Finally, with a working `objtool`, it removes the disable of kernel stack validation in cross builds, previously introduced in c3e31b6a9b04 and later updated in 5f8e5872406d and 802bfe080678. These patches were predicated on `objtool` not being portable to non-Linux build environments, but in particular in light of the `objtool` fix in this series, that concern no longer applies.

### CODE REVIEW

File: target/linux/generic/hack-6.18/202-objtool_portability.patch [hunk 1]
```diff
@@ -0,0 +1,64 @@
...
+ 	return false;
+ }
+ 
++static ssize_t call_sendfile(int out_fd, int in_fd, off_t *offset, size_t count)
++{
++#ifdef __linux__
++	return sendfile(out_fd, in_fd, offset, count);
++#else
++	off_t len;
++	int rv = sendfile(out_fd, in_fd, *offset, &len, NULL, 0);
```
Comment (openwrt-ai) [inline target/linux/generic/hack-6.18/202-objtool_portability.patch]: The non-Linux `sendfile()` branch can't actually copy here. On macOS/Darwin the prototype is `int sendfile(int fd, int s, off_t offset, off_t *len, struct sf_hdtr *hdtr, int flags)` where `fd` is the source file and `s` must be a connected `SOCK_STREAM` socket — it cannot send to a regular file. `copy_file()` is called with two regular files (`copy_file(objname, opts.output)` and the backup path), and objtool is invoked with `--output` for objects during the kernel build, so this branch would fail with `ENOTSOCK` on the build hot path rather than copy the `.o`.

Two further problems even setting that aside:
- Argument order is reversed vs. the Darwin prototype: the patch passes `out_fd` as `fd` (the file to read) and `in_fd` as `s` (the socket), i.e. source and destination are swapped relative to BSD semantics.
- `len` is passed uninitialized; on Darwin `*len` is in/out and specifies the number of bytes to send on entry, so its value is undefined here.

Since macOS `sendfile` is socket-only, it can't implement a file-to-file copy at all. Consider replacing the non-Linux branch with a plain `read()`/`write()` loop (or `fcopyfile()` on Darwin) instead of `sendfile()`.

---
_Generated by [Claude Code](https://claude.ai/code)_

**Review by openwrt-ai — COMMENTED** [review]
Reviewed 3 new commits; one inline issue on the objtool `sendfile` portability shim. Commit messages match their diffs.

---
_Generated by [Claude Code](https://claude.ai/code)_

File: target/linux/generic/hack-6.18/202-objtool_portability.patch (hunk 1 above)
Comment (markmentovai) [reply target/linux/generic/hack-6.18/202-objtool_portability.patch]: Updated to a more portable read-write loop.

File: target/linux/generic/hack-6.18/202-objtool_portability.patch [hunk 2]
```diff
@@ -0,0 +1,93 @@
...
+ 
++#ifndef __linux__
++#define RETRY_EINTR(x)                                      \
++  ({                                                        \
++    __typeof__(x) eintr_wrapper_result;                     \
++    do {                                                    \
++      eintr_wrapper_result = (x);                           \
++    } while (eintr_wrapper_result == -1 && errno == EINTR); \
++    eintr_wrapper_result;                                   \
++  })
```
Comment (openwrt-ai) [inline target/linux/generic/hack-6.18/202-objtool_portability.patch]: nit: the `RETRY_EINTR` macro is indented with 2 spaces, while the rest of this patch and objtool/kernel code use tabs. Re-indent with tabs for consistency with the surrounding file.

---
_Generated by [Claude Code](https://claude.ai/code)_

**Review by openwrt-ai — COMMENTED** [review]
Reviewed 1 updated commit since the last review. The objtool `copy_file` shim was rewritten from the broken non-Linux `sendfile()` call into a `read()`/`write()` loop, correctly addressing the prior review comment; the new logic (EINTR retry, short-write handling, premature-EOF check) is sound. One minor style nit inline. Commit messages match their diffs.

---
_Generated by [Claude Code](https://claude.ai/code)_

File: target/linux/generic/hack-6.18/202-objtool_portability.patch [hunk 3]
```diff
@@ -0,0 +1,93 @@
+From bd04dba44360b537ec0ef20881d8b36523690355 Mon Sep 17 00:00:00 2001
+From: Mark Mentovai <mark@mentovai.com>
+Date: Mon, 1 Jun 2026 09:11:43 -0400
+Subject: [PATCH] objtool: fix build on macOS hosts
+
+Since 5a406031d0719 (2025-03-17, in 6.15), objtool calls sendfile, but
+sendfile is Linux-specific and a sendfile with the requisite
+capabilities is not available on other other operating systems. Provide
```
Comment (httpstorm) [inline target/linux/generic/hack-6.18/202-objtool_portability.patch]: Repeated word `other`. Also apply to the outer patch.
```suggestion
capabilities is not available on other operating systems. Provide
```

**Review by openwrt-ai — COMMENTED** [review]
Reviewed 3 new commits; no new issues found.

The change since the last review is limited to re-indenting the `RETRY_EINTR` macro and the `read()`/`write()` calls with tabs (resolving the prior nit) plus the `| O_LARGEFILE` continuation in the gen_init_cpio patch, with corresponding patch hunk-header/insertion-count and `From`/`index` metadata refreshed. Verified the hunk arithmetic is internally consistent (objtool: 2+16+22 = 40 insertions; gen_init_cpio hunks unchanged in count) and that all hunk context still matches the v6.18.33 reference tree (`usr/gen_init_cpio.c`, `tools/objtool/builtin-check.c`), so both quilt patches still apply. Both prior review threads are resolved and the copy-loop logic is unchanged.

---
_Generated by [Claude Code](https://claude.ai/code)_

**Review by httpstorm — CHANGES_REQUESTED** [review]

**Comment by httpstorm** [comment]
@markmentovai 
Thank you very much for the fix.
Build and run tested: target `x64`, host macOS 15.7.7 x64.
Build tested: target `mvebu/cortexa9/WRT3200ACM`, host macOS 15.7.7 x64.
I also isolated the `sendfile` code, added debug messages and ran it as a separate program, because I was curious how the `RETRY_EINTR` macro returns a value. It works correctly.

File: target/linux/generic/hack-6.18/202-objtool_portability.patch (hunk 3 above)
Comment (markmentovai) [reply target/linux/generic/hack-6.18/202-objtool_portability.patch]: Thanks! Fixed, updated.

**Review by httpstorm — APPROVED** [review]

**Review by openwrt-ai — COMMENTED** [review]
Reviewed 3 new commits; no new issues found.

Since the last review the PR was rebased and the only substantive delta is patch-metadata cleanup: both quilt patches had their `git format-patch` artifacts stripped (`diff --git`/`index` lines and the trailing `-- /2.54.0` footer), the objtool commit-message typo "other other operating systems" was fixed, and the hunk-header context strings were trimmed. Confirmed both patches still apply at `--fuzz=0` against the v6.18.34 reference tree (`usr/gen_init_cpio.c`, `tools/objtool/builtin-check.c`), and the `copy_file` read()/write() fallback loop is unchanged from the previously-reviewed, sound version. Commit messages match their diffs.

---
_Generated by [Claude Code](https://claude.ai/code)_

**Comment by robimarko** [comment]
Thanks! Rebased on top of main and merged!
