### PR TITLE
tools: gnulib: do not cache C standard option test results

### PR DESCRIPTION
**Pull request by mcprat**
@httpstorm @robimarko fixing the most unusual regression from #16522 

After eliminating the possibility of automake having a bug by testing a revert to the recent updates to automake, the problems regarding autoreconf with some packages was bisected to the gnulib update instead, through aclocal macros.

With the new module, std-gnu23, some packages are failing build due to both the host compiler and cross compiler being tested for availability of C23 standard features with the configure script. The results of one is being cached and used for the other, while the two compilers are different versions and may or may not both support C23 options and would otherwise have conflicting results.

Creating unique variables for each compiler tested is a difficult task and may require a much larger patch, therefore, just remove the caching.

A similar patch may have to be done
for the next release of Autoconf
if upstream GNU does not accept this solution.

### CODE REVIEW

**Comment by mcprat** [comment]
there might still be a problem where the last most recent test is yes but the previous was no

**Comment by httpstorm** [comment]
I tested without the recent `libsodium` [fix](https://github.com/openwrt/packages/pull/27123) `TARGET_CFLAGS += -std=gnu17` and it fails same as before:

``` C
<command-line>: error: unknown type name 'thread_local'; did you mean 'pthread_rwlock_t'?
randombytes/internal/randombytes_internal_random.c:136:8: note: in expansion of macro 'TLS'
  136 | static TLS InternalRandom stream = {
      |        ^~~
randombytes/internal/randombytes_internal_random.c:136:27: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'stream'
  136 | static TLS InternalRandom stream = {
      |                           ^~~~~~
```

`-std=gnu23` is present in the `libsodium` Makefile
``` Makefile
CC = arm-openwrt-linux-muslgnueabi-gcc -std=gnu23
CCAS = arm-openwrt-linux-muslgnueabi-gcc -std=gnu23
```

[2025-08-02 aclocal.tar.gz](https://httpstorm.com/openwrt/test/2025-05-07_maintainer-clean/2025-08-02%20aclocal.tar.gz)
[2025-08-02 libsodium-1.0.20.tar.gz](https://httpstorm.com/openwrt/test/2025-05-07_maintainer-clean/2025-08-02%20libsodium-1.0.20.tar.gz)

**Comment by robimarko** [comment]
This fixes strace

**Comment by PolynomialDivision** [comment]
> A similar patch may have to be done
> for the next release of Autoconf
> if upstream GNU does not accept this solution.

If you already sent that upstream, why not include a proper patch with a patch header and everything? I'm just a fan of having a patch that's easy to apply and comes with a clear description, so you don’t have to dig through history to figure out what it's for.

**Comment by mcprat** [comment]
I didn't send it yet, and I'm thinking that another change might be necessary but not sure.

**Comment by PolynomialDivision** [comment]
I would suggest merging this to finally fix ci and than replace it later by your upstream patch? By the way thanks a lot for all your work (cc @robimarko , @hauke )

**Comment by mcprat** [comment]
This is ready, I was thinking too hard about it, this is the only patch needed.

I built `strace` myself and inspected the configure script carefully

Autoconf uses the same variable for the individual test
`ac_cv_prog_cc_c23`

however, when the option is saved back to the compiler command that is used later,
there are already unique variables involved: host uses `$CC`, target uses `$CC_FOR_BUILD`

for host before test
`ac_save_CC=$CC`
`CC="$ac_save_CC $ac_arg"`

for host after test
`CC="$CC $ac_cv_prog_cc_c23"`
`ac_cv_prog_cc_stdc=$ac_cv_prog_cc_c23`

for target before test
`ac_save_CC=$CC_FOR_BUILD`
`CC_FOR_BUILD="$ac_save_CC $ac_arg"`

target after test
`CC_FOR_BUILD="$CC_FOR_BUILD $ac_cv_prog_cc_c23"`
`ac_cv_build_prog_cc_stdc=$ac_cv_prog_cc_c23`

**Comment by mcprat** [comment]
> I tested without the recent [`libsodium` fix](https://github.com/openwrt/packages/pull/27123) `TARGET_CFLAGS += -std=gnu17` and it fails same as before:

Like I said elsewhere, I believe that unfortunately, `libsodium` just does not support the new C standard,
while the compiler does, so the fix to manually set the C standard is the only way for that one.

**Comment by mcprat** [comment]
the only change is commit message

**Comment by PolynomialDivision** [comment]
Thanks! Rebased on top of main and merged!

**Comment by httpstorm** [comment]
@mcprat 

> Like I said elsewhere, I believe that unfortunately, libsodium just does not support the new C standard,
while the compiler does, so the fix to manually set the C standard is the only way for that one.

Then all is good. I completed the build successfully. I'm sorry for the confusion.
