### PR TITLE
generic: phy: adm6996: fix build on 6.18 kernel

### PR DESCRIPTION
**Pull request by DragonBluep**
devm_gpio_request() was removed since kernel 6.17. Convert it to devm_gpio_request_one() to fix:

target/linux/generic/files/drivers/net/phy/adm6996.c: In function 'adm6996_gpio_probe': target/linux/generic/files/drivers/net/phy/adm6996.c:1183:15: error: implicit declaration of function 'devm_gpio_request'; did you mean 'devm_gpio_request_one'? [-Wimplicit-function-declaration]
 1183 |         ret = devm_gpio_request(&pdev->dev, priv->eecs, "adm_eecs");
      |               ^~~~~~~~~~~~~~~~~
      |               devm_gpio_request_one

Link: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=linux-6.18.y&id=a5589313383074c48a1b3751d592a6e084ae0573

### CODE REVIEW

**Comment by robimarko** [comment]
Thanks! Rebased on top of main and merged!
