### PR TITLE
package/libs/nettle: Update to 3.5.1

### PR DESCRIPTION
**Pull request by diizzyy**
Update (lib)nettle to 3.5.1
Bump ABI_VERSION

Signed-off-by: Daniel Engberg <daniel.engberg.lists@pyret.net>

### CODE REVIEW

**Comment by diizzyy** [comment]
Compile tested: ipq40xx, Linksys EA6350v3, OpenWrt master
Run tested: ipq40xx, Linksys EA6350v3, OpenWrt master

**Comment by EXSERENS** [comment]
Compile tested: mvebu, Linksys WRT3200ACM, OpenWrt master
Run tested: mvebu, Linksys WRT3200ACM, OpenWrt master

**Comment by dedeckeh** [comment]
dnsmasq fails to compile with version 3.5.1
crypto.c: In function 'dnsmasq_ecdsa_verify':
crypto.c:297:36: error: 'nettle_secp_256r1' undeclared (first use in this function); did you mean 'nettle_get_secp_256r1'?
    nettle_ecc_point_init(key_256, &nettle_secp_256r1);
                                    ^~~~~~~~~~~~~~~~~
                                    nettle_get_secp_256r1
crypto.c:297:36: note: each undeclared identifier is reported only once for each function it appears in
crypto.c:310:36: error: 'nettle_secp_384r1' undeclared (first use in this function); did you mean 'nettle_secp_256r1'?
    nettle_ecc_point_init(key_384, &nettle_secp_384r1);
                                    ^~~~~~~~~~~~~~~~~
                                    nettle_secp_256r1

Despite clear statements in ecc_curve.h 3.4.1 dnsmasq refers to structures; made pirvate in 3.5.1; iso using accessor functions ...

**Comment by dedeckeh** [comment]
Patch pushed to master (https://git.openwrt.org/?p=openwrt/openwrt.git;a=commit;h=9e489b41b596a768b04b796a9b375d7d005b6ec7); thx
