### ISSUE TITLE
kernel: status of 6.18 version

### ISSUE THREAD

**Issue by namiltd** [openwrt/openwrt#21030]
***Please do not edit but provide new information in the thread.***

### Status of Linux kernel 6.18 migration in main: ###

**Currently implemented release: 6.18**

- [ ] generic: 
  - under development: https://github.com/openwrt/openwrt/pull/20965

**Targets:**
- [ ] airoha
  - under development: https://github.com/openwrt/openwrt/pull/21019
- [ ] apm821xx
- [ ] armsr
- [ ] at91
- [ ] ath79
- [ ] bcm27xx
- [ ] bcm47xx
- [ ] bcm4908
- [ ] bcm53xx
- [ ] bmips
- [ ] d1
- [ ] econet
- [ ] gemini
- [ ] imx
- [ ] ipq40xx
- [ ] ipq806x
- [ ] ixp4xx
- [ ] kirkwood
- [ ] lantiq
- [ ] layerscape
- [ ] loongarch64
- [ ] malta
  - under development: https://github.com/openwrt/openwrt/pull/20965
- [ ] mediatek
- [ ] mpc85xx
- [ ] mvebu
- [ ] mxs
- [ ] octeon
- [ ] omap
- [ ] pistachio
- [ ] qoriq
- [ ] qualcommax
- [ ] qualcommbe
- [ ] ramips
- [ ] realtek
- [ ] rockchip
- [ ] sifiveu
- [ ] siflower
- [ ] starfive
- [ ] stm32
- [ ] sunxi
- [ ] tegra
- [ ] uml
- [ ] x86
- [ ] zynq

Complete 0 of 45
### Summary:

- generic
  - &ensp;1 - under development
  - &ensp;0 - approval request
  - &ensp;0 - ✓ approved
- targets 
  - &ensp;2 - under development
  - &ensp;0 - approval request for testing
  - &ensp;0 - ✓ as testing
  - &ensp;0 - approval request for default
  - &ensp;0 - ✓ as default

Total 2 of 45

---
### Additional pending patches related to kernel 6.18:
 -  https://github.com/openwrt/openwrt/pull/20964

**Comment by mrkiko** [comment]
Mark.

**Comment by peterwillcn** [comment]
Now, Linux 6.18 LTS release!

**Comment by castillofrancodamian** [comment]
Missing [x86](https://github.com/openwrt/openwrt/pull/21078).

**Comment by castillofrancodamian** [comment]
The new target [microchipsw](https://github.com/openwrt/openwrt/tree/main/target/linux/microchipsw) is missing from the list. "Generic" is also missing from the accounting for "Total 4 of 46".

**Comment by LearZhou** [comment]
Marked to be noticed later.

**Comment by jonasjelonek** [comment]
realtek target support for 6.18 is being worked on: #21181

**Comment by graysky2** [comment]
https://github.com/openwrt/openwrt/pull/21206

**Comment by graysky2** [comment]
Maybe related have not tried on 6.12.y: https://github.com/openwrt/openwrt/pull/21223

**Comment by graysky2** [comment]
https://github.com/openwrt/rtl8168/issues/1

**Comment by graysky2** [comment]
https://github.com/openwrt/packages/pull/28167

**Comment by graysky2** [comment]
https://github.com/openwrt/telephony/pull/930

**Comment by graysky2** [comment]
https://github.com/openwrt/openwrt/pull/21302

**Comment by graysky2** [comment]
https://github.com/openwrt/mt76/pull/1026

**Comment by graysky2** [comment]
The following are currently broken when building for x86/64:
package/kernel/rtl8812au-ct
package/kernel/ath10k-ct

**Comment by graysky2** [comment]
https://github.com/openwrt/packages/pull/28223

**Comment by Neustradamus** [comment]
@namiltd: Thanks for your work and Happy New Year 2026!

**Comment by namiltd** [comment]
The rtl8812au-ct driver is obsolete and replaced by rtw88, I suggest removing it completely from OpenWRT.

**Comment by graysky2** [comment]
I have been spending time today trying to update it and finding it to be a terrible task. I am happy to remove it. What about `ath10k-ct`

**Comment by namiltd** [comment]
Simply add `DEPENDS:=@!LINUX_6_18` to `define KernelPackage/rtl8812au-ct`

**Comment by graysky2** [comment]
Would be great if anyone building and running x86 could share experiences good or bad. I have it running on my Intel N150 based router with no obvious regressions or broken functionality (router/firewall with VLANs, wireguard, pbr, nfs, samba, lxc with multiple containers, snort3). Best to comment in the PR: https://github.com/openwrt/openwrt/pull/21078

**Comment by mgz0227** [comment]
> Would be great if anyone building and running x86 could share experiences good or bad. I have it running on my Intel N150 based router with no obvious regressions or broken functionality (router/firewall with VLANs, wireguard, pbr, lxc with multiple containers, snort3). Best to comment in the PR: [#21078](https://github.com/openwrt/openwrt/pull/21078)

I’ve been running it on an Intel N305 and everything looks good so far. No regressions noticed in my setup.

**Comment by mcbridematt** [comment]
I have started working on 6.18 for armsr:
https://github.com/openwrt/openwrt/pull/21433

**Comment by mrnuke** [comment]
I'll take qualcommbe for v6.18: https://github.com/openwrt/openwrt/pull/21506

@namiltd, when do you expect to have the generic support for 6.18 merged?

**Comment by castillofrancodamian** [comment]
The total counter is outdated. It should be 9 instead of 8.

**Comment by namiltd** [comment]
> when do you expect to have the generic support for 6.18 merged?

@mrnuke Unfortunately, it doesn't depend on me, but on the developers who have to find the will and time for it.

**Comment by andrewjlamarche** [comment]
> Unfortunately, it doesn't depend on me, but on the developers who have to find the will and time for it.

I think the ask is, since you created the 6.18 generic PR, when do you expect it will be ready and merged?

**Comment by namiltd** [comment]
In my opinion, it is ready, but others have to confirm this.

**Comment by peterwillcn** [comment]
[Linus Torvalds Confirms The Next Kernel Is Linux 7.0](https://www.reddit.com/r/linux/comments/1qzqbqm/linus_torvalds_confirms_the_next_kernel_is_linux/)

**Comment by namiltd** [comment]
But the next LTS won't be released until December. The latest LTS version is still 6.18.

**Comment by ngc7331** [comment]
Hi, I tried to add starfive support for 6.18 and booted on my Milk-V Mars CM board #22063. This is my first time doing these, please let me know if I've made any mistakes.

**Comment by namiltd** [comment]
The stable OpenWrt-25.12.0 release is almost here (planned date March 5, 2026), maybe now it will be time to implement kernel 6.18.

**Comment by namiltd** [comment]
I had false hope that something would work out. I just have to be patient.

**Comment by mgz0227** [comment]
At this rate, maybe it’ll jump straight to 7.x 😂

**Comment by namiltd** [comment]
This would be possible if it received LTS status, i.e. around 7.3.

**Comment by mgz0227** [comment]
At the current pace, Kernel 7.3 will probably be around October.
<img width="1137" height="856" alt="Image" src="https://github.com/user-attachments/assets/6f7a1999-6f52-4015-a1a4-5a1a67a2d192" />

**Comment by namiltd** [comment]
@robimarko What are we waiting for?

**Comment by robimarko** [comment]
For the 25.12 release to settle down.

6.18 is the next thing

**Comment by lorand-horvath** [comment]
Perhaps a naive question... can anybody list a few reasons why 6.18 would be better than 6.12 for, let's say, a MediaTek Filogic unit or an older unit with 16 MB of flash (e.g. WNDR3800), or even 8 MB-only (WR1043ND v3)?
I'm wondering because moving from 6.6 to 6.12 increased the image sizes quite a bit, so I assume 6.12 -> 6.18 will have the same effect.
Thanks!

**Comment by namiltd** [comment]
Just changing the kernel version slightly increases the image size. I noticed a much larger increase when changing the backports/mac80211 version.

**Comment by hailfinger** [comment]
#21078 has been merged.

**Comment by graysky2** [comment]
@namiltd - plz update with recent merging 🥳

**Comment by namiltd** [comment]
There was a bit of confusion with the approval order, but I'm glad my work was approved.

**Comment by namiltd** [comment]
After months of testing, the Ramips (https://github.com/openwrt/openwrt/pull/21418)  and Malta (https://github.com/openwrt/openwrt/pull/20965) targets are awaiting approval.

**Comment by castillofrancodamian** [comment]
Kirkwood's [PR](https://github.com/openwrt/openwrt/pull/22680) is to switch directly to 6.18, not just "add".

**Comment by HyperdrivzZ** [comment]
When will ipq40xx/generic will get a kernal update?

**Comment by namiltd** [comment]
@HyperdrivzZ Ask about it inside PR https://github.com/openwrt/openwrt/pull/21809.

**Comment by libiunc** [comment]
Siflower's 6.18 version compiles normally, but the device fails to boot(from bpi-rv2),bootlog indicating a problem with eth driver.Everything works fine after disabling it,

**Comment by castillofrancodamian** [comment]
New Alpine target in development in https://github.com/openwrt/openwrt/pull/23189.

**Comment by kylehendrydev** [comment]
I have a WIP bcm47xx branch here:
https://github.com/kylehendrydev/openwrt/tree/bcm47xx-6.18

Right now I'm stuck on an mm bug (see attached)

[bcm4718-6.18-crash.txt](https://github.com/user-attachments/files/27560356/bcm4718-6.18-crash.txt)

**Comment by jmv2009** [comment]
@kylehendrydev: CONFIG_PAGE_BLOCK_MAX_ORDER=10
CONFIG_SLUB_TINY=y

**Comment by castillofrancodamian** [comment]
Tegra update under development by [tmn505](https://github.com/tmn505/openwrt/tree/tegra-next).

**Comment by httpstorm** [comment]
@namiltd @PolynomialDivision @robimarko @Ansuel @hauke @dangowrt @mcprat 

This commit c73bb851d54cafd0234a4b78aa6adb779dd5c44d breaks the build on macOS 15.7.5 x64. If I revert to `linux-6.12`, everything builds fine.
build log: [linux-6.18-sendfile.txt](https://httpstorm.com/openwrt/test/2026-05-11_linux-sendfile/linux-6.18-sendfile.txt)
``` C
builtin-check.c:13:10: fatal error: 'sys/sendfile.h' file not found
   13 | #include <sys/sendfile.h>
      |          ^~~~~~~~~~~~~~~~
```

``` bash
find . | grep 'sendfile\.h'
./build_dir/toolchain-x86_64_gcc-14.3.0_musl/musl-1.2.5/include/sys/sendfile.h
./staging_dir/toolchain-x86_64_gcc-14.3.0_musl/include/sys/sendfile.h
```

**Comment by namiltd** [comment]
@httpstorm  Solutions to problems with individual targets should be sought in the appropriate PRs or a separate Issue should be created, not here.
Your problem is related to compilation problems on macOS and not the x86 target itself. Create a new issue.

**Comment by mcprat** [comment]
well it's definitely kernel related...

does it happen on other targets @httpstorm ?

**Comment by hurrian** [comment]
6.18 as default for airoha: #23640

**Comment by testuser7** [comment]
Is anyone working on migration for qualcommax?

**Comment by namiltd** [comment]
If I had known about it, I would have marked it on the list.

**Comment by chunkeey** [comment]
https://github.com/openwrt/openwrt/pull/23649 - UML as testing v6.18

**Comment by joshuacov1** [comment]
I've update the bcm27xx to 6.18 and started an approval-process under #23703 .

**Comment by naseef** [comment]
#23755 econet testing kernel v6.18

**Comment by naseef** [comment]
econet 6.18 as default #23879

**Comment by hurrian** [comment]
qualcommbe 6.18 as default #23908

**Comment by httpstorm** [comment]
@namiltd 
Hey, I apologise for asking here, but can you please join this conversation: https://github.com/openwrt/openwrt/pull/23631
Other people also reported they cannot build the main branch after the switch to `linux-6.18`, because the `iptables` package you added installs duplicated files.

**Comment by pktpls** [comment]
A little pedantic but total count should be 42 of 48 :)))

There are 6 targets not yet in progress: at91, bcm4908, bmips, imx, loongarch64, qualcommax

**Comment by castillofrancodamian** [comment]
[qualcommax](https://github.com/openwrt/openwrt/pull/24031).

**Comment by jonasjelonek** [comment]
It seems development of the new alpine target has been moved to https://github.com/openwrt/openwrt/pull/24057

**Comment by mcbridematt** [comment]
PR for making 6.18 default on armsr: https://github.com/openwrt/openwrt/pull/24355

**Comment by namiltd** [comment]
The work on implementing kernel 6.18 is progressing very slowly, and the next LTS version, which will be kernel 7.4 or 7.5, is very close.

**Comment by castillofrancodamian** [comment]
And what does that matter? This situation has already happened in the past. It's almost the end of the road. Even closer than 6.12.

**Comment by andrewjlamarche** [comment]
Is there a timeline for OpenwWrt 26.x? It looks like a few targets are going to be dropped as of right now…

**Comment by pktpls** [comment]
Given that loongarch64 has only a generic image, is it acceptable to test a 6.18 port only in QEMU?

**Comment by namiltd** [comment]
@pktpls  The most reliable tests are those performed on real hardware. Ask @hackpascal  for help with testing.

**Comment by dangowrt** [comment]
> Given that loongarch64 has only a generic image, is it acceptable to test a 6.18 port only in QEMU?

Yes. You need a custom ED2K build to actually boot the image, but that's doable. Let me know if you need any help with that.

**Comment by jmv2009** [comment]
The current snapshot loonarch64 runs fine in QEMU (video=VGA) [without getting immediately keyboard, network to work]

**Comment by pktpls** [comment]
loongarch64 WIP: https://github.com/pktpls/openwrt/commits/loongarch64-6.18/

**Comment by jmv2009** [comment]
@pktpls: at least your loongarch64-6.18 seems to boot in QEMU

**Comment by pktpls** [comment]
loongarch64 6.18 as testing: #24460

**Comment by chunkeey** [comment]
uml 6.18 as the default kernel: https://github.com/openwrt/openwrt/pull/24523

**Comment by castillofrancodamian** [comment]
New target [asr1802s](https://github.com/openwrt/openwrt/pull/24614).

**Comment by badulesia** [comment]
mpc85xx has switched to 6.18
https://github.com/openwrt/openwrt/commit/34e6f59b909406927c9483a0c909942cdebb94d5

**Comment by castillofrancodamian** [comment]
New target [mdm9607](https://github.com/openwrt/openwrt/pull/24731).

**Comment by sch-m** [comment]
imx as testing: #24807

**Comment by castillofrancodamian** [comment]
New target [cortina](https://github.com/openwrt/openwrt/pull/25033).

**Comment by joshuacov1** [comment]
bcm27xx: switch to 6.18: https://github.com/openwrt/openwrt/pull/25037

**Comment by chunkeey** [comment]
uml: 6.18 is now the default. 056f9ff

**Comment by GoetzGoerisch** [comment]
As no one is working on `at91` and `bmips`, should those targets be dropped?
I bumped `at91` to `6.12` without much testing feedback.

**Comment by abajk** [comment]
> I bumped `at91` to `6.12` without much testing feedback.

The at91 is a fully upstreamed target, so upgrading the kernel version should be straightforward. I think there is a dev board with a sama5 SoC at my work. I'll try to borrow it and see what can be done.

**Comment by andrewjlamarche** [comment]
I don't have any bmips devices to test, but I made a PR that builds. Would love for others to try https://github.com/openwrt/openwrt/pull/25293
