### ISSUE TITLE
FS#1359 - boost falis to compile with glibc 2.26 

### ISSUE THREAD

**Issue by openwrt-bot** [openwrt/openwrt#6289]
*atyg02:*

Environment: x86_64, OpenWRT/LEDE trunk
Description: Compilation failed with target-x86_64_glibc
<code>
# Target System                                              --> x86
# Subtarget                                                     --> x86_64
# Target Profile                                               --> Generic

# Advanced configuration options (for developers)     [*]   Toolchain Options  ---> C Library implementation (Use glibc)  

if I select only --> <*> boost -- it compiled with no issues.

But if I try to include the following Boost library, then failed to compile.
--> <*> boost.................................. Boost C++ source library packages
                       --> Select Boost libraries
                                            --> -*- Boost atomic library   
                                            --> -*- Boost chrono library
                                            --> -*- Boost system library
                                            --> -*- Boost thread libray

</code>
according to this [[https://github.com/openwrt/packages/issues/5573]], glibc 2.26 has introduced a regression and needs to be patched.
do you have any idea how to solve the issue?
Thank you !

**Comment by KanjiMonster** [comment]
The referenced issue has been closed as fixed, so closing this accordingly.
