### PR TITLE
kexec-tools: fix multiple compile errors

### LINKED ISSUE #14621: kexec-tools fails to build with binutils-2.42
### Describe the bug

Patch already exists for binutils-2.41 but doesn't apply cleanly;
I made changes by hand and it fixes the build.

Patch is available here: https://www.mail-archive.com/kexec@lists.infradead.org/msg32771.html

### Terms

- [x] I am reporting an issue for OpenWrt, not an unsupported fork.

### PR DESCRIPTION
**Pull request by guidosarducci**
Add two patches to fix compile errors being repeatedly seen on OpenWrt CI.

The first is an upstream backport to fix this i386-related error:
```
  x86_64-openwrt-linux-musl-gcc  -mcmodel=large -I./purgatory/include
  -I./purgatory/arch/x86_64/include -I./util_lib/include -I./include -Iinclude
  -I/builder/shared-workdir/build/sdk/staging_dir/toolchain-x86_64_gcc-13.3.0_musl/lib/gcc/x86_64-openwrt-linux-musl/13.3.0/include
  -c -MD -o purgatory/arch/i386/entry32-16.o purgatory/arch/i386/entry32-16.S
  purgatory/arch/i386/entry32-16.S: Assembler messages:
  purgatory/arch/i386/entry32-16.S:23: Error: 64bit mode not supported on `i386'.
```
The second addresses an error using basename() on musl libc:
```
  kexec/arch/i386/x86-linux-setup.c: In function 'add_edd_entry':
  kexec/arch/i386/x86-linux-setup.c:332:20: warning: implicit declaration of function 'basename' [-Wimplicit-function-declaration]
    332 |         if (sscanf(basename(sysfs_name), "int13_dev%hhx", &devnum) != 1) {
        |                    ^~~~~~~~
  kexec/arch/i386/x86-linux-setup.c:332:20: warning: passing argument 1 of 'sscanf' makes pointer from integer without a cast [-Wint-conversion]
    332 |         if (sscanf(basename(sysfs_name), "int13_dev%hhx", &devnum) != 1) {
        |                    ^~~~~~~~~~~~~~~~~~~~
        |                    |
        |                    int
  ...
```

Fixes: #14621

### CODE REVIEW

**Comment by namiltd** [comment]
Partially duplicates: https://github.com/openwrt/openwrt/pull/15650

**Comment by guidosarducci** [comment]
@PolynomialDivision @Ansuel This should fix the CI problems I mentioned in https://github.com/openwrt/openwrt/pull/15639#issuecomment-2154307314. Please have a look, since the issues are blocking other PRs.

**Comment by namiltd** [comment]
@guidosarducci To avoid duplication, maybe leave only 020-i386-improve-basename-compatibility.patch in your PR?
