### PR TITLE
uboot-sunxi: add missing type __u64

### PR DESCRIPTION
**Pull request by httpstorm**
Non Linux systems e.g. macOS lack the __u64 type and produce build errors:
In file included from tools/aisimage.c:9:
In file included from include/image.h:19:
In file included from ./arch/arm/include/asm/byteorder.h:29:
In file included from include/linux/byteorder/little_endian.h:13:
include/linux/types.h:146:9: error: unknown type name '__u64'; did you mean '__s64'?
typedef __u64 __bitwise __le64;

Resolved by declaring __u64 in include/linux/types.h
Build tested on macOS and Ubuntu.
Target System (Allwinner A1x/A20/A3x/H3/H5/R40)
Subtarget (Allwinner A20/A3x/H3/R40)
Target Profile (Xunlong Orange Pi Zero)

@wigyori @nbd168 @neheb

### CODE REVIEW

**Comment by hauke** [comment]
Thank you for the pull request, it was added to master.

**Comment by httpstorm** [comment]
Thank you, @hauke !
The issue is resolved.
I am sorry for the late replay! There were unrelated build errors, that prevented me from testing earlier, and it took me some time to resolve them:
- bpftools: fix param order for install on macOS - I made a pull request  https://github.com/openwrt/openwrt/pull/3959
- ntfs-3g broken by https://github.com/openwrt/openwrt/commit/f439e291304a93b982e912dc91b80ca950a594f3 - Issue https://github.com/openwrt/packages/issues/14940
