### PR TITLE
mbedtls: restore previous configuration behavior

### PR DESCRIPTION
**Pull request by 1715173329**
Fallback to default mbedtls configurations in case of the package is not configured.
It is possible for some reasons it get built even if it's unselected because of build system bugs or other build-only dependencies.
In this case current behavior will comment out all necessary configurations and lead build errors.

Fixes: 5359639c2b74 ("mbedtls: Apply configuration in Configure instead of Prepare")

### CODE REVIEW

**Comment by 1715173329** [comment]
Cc: @hauke

**Comment by drujd** [comment]
I can confirm this fixes my openssl-based build. Without this I get an mbedtls compilation error (mbedtls should not be needed at all).

**Comment by egc112** [comment]
I can confirm that this PR fixes my OpenSSL build which was broken due to https://github.com/openwrt/openwrt/commit/5359639c2b743be800ebe075936946c48635333a

**Comment by hnyman** [comment]
+1 also from me.
This fixes the newly broken mbedtls in openssl-based builds.

(As a side note, the indirect (build-time?) pull-in of mbedtls into otherwise openssl-only based compilation is a rather new quirk. Mbedtls package does not even end into the final binary, but is apparently required by something during the build process.)

**Comment by hauke** [comment]
Thanks, probably something has an unconditional build dependency on mbedtls.
