### PR TITLE
airoha: fix target building

### PR DESCRIPTION
**Pull request by mkshevetskiy**
Commit 7865e4bfae97f697ac0c4de450c8bd932a6f8bd4 ("airoha: replace multi serdes patch with upstream kernel version") breaks airoha board building with the following symptoms:

 drivers/net/ethernet/airoha/airoha_eth.c:11:10: fatal error: linux/pcs/pcs.h: No such file or directory
   11 | #include <linux/pcs/pcs.h>
      |          ^~~~~~~~~~~~~~~~~
 compilation terminated.

This can be fixed by two ways:
 * revert guilty commit
 * add missed PCS/phylink patches.

This patch implements a second way. Missed patches were taken from upstream openwrt.

### CODE REVIEW

**Comment by mkshevetskiy** [comment]
@robimarko, could you look on it. OpenWrt-25.12 for airoha is severely broken.

**Review by openwrt-ai — COMMENTED** [review]
## Commit checks

- `9ee1864` **airoha: fix target building** — The change is a faithful backport. All added generic patches match current openwrt `main` verbatim (byte-for-byte): `backport-6.12/{650,651,652,653-01,653-02,702}` and `pending-6.12/770-01..770-07`. The `706` and airoha `310-09` edits are only refreshed hunk offsets, and the `310-08` → `pending-6.12/770-07` rename mirrors main's structure. `601-v7.1-net-add-netdev_from_priv-helper.patch` is a correct 6.18→6.12 adaptation of main's patch — only its hunk header changed (`2754`→`2605`) and it re-anchors cleanly to `include/linux/netdevice.h` (`netdev_priv` at line 2603 in v6.12.103). No code/logic issues.

  Two smaller points:
  - Backport to `openwrt-25.12` is missing the `(cherry picked from commit ...)` trailer(s) identifying the upstream openwrt commits these patches originate from. This is required for stable-branch backports (also raised by the formality bot; a maintainer can override via `[allow cherry-pick]`). Because this is a curated multi-patch set rather than a single cherry-pick, listing the source commit per patch group would help maintainers verify provenance.
  - Commit-body typo: "Missed patches were taken from upsream openwrt." → "upstream".

---
_Generated by [Claude Code](https://claude.ai/code)_

**Comment by mkshevetskiy** [comment]
@LorenzoBianconi, @Ansuel, @csharper2005, @danpawlik, @danielschwierzeck

**Comment by robimarko** [comment]
I dont think you can just backport this, there are per target DTS fixes required as well as the PCS property changed

**Comment by YaleiZang** [comment]
hi,Mikhail . I have already backported the relevant patches to 25.12 in this PR , https://github.com/openwrt/openwrt/pull/24823 ,
It is currently under review and has been tested to work properly.

File: target/linux/generic/pending-6.12/770-04-net-pcs-implement-Firmware-node-support-for-PCS-driv.patch [hunk 1]
```diff
@@ -0,0 +1,384 @@
...
++	return index > 0 ? 0 : -ENOENT;
++}
++
++int fwnode_phylink_pcs_parse(struct fwnode_handle *fwnode,
++			     struct phylink_pcs **available_pcs,
++			     unsigned int *num_pcs)
++{
++	int i;
++
++	if (!fwnode_property_present(fwnode, "pcs-handle"))
```
Comment (openwrt-ai) [inline target/linux/generic/pending-6.12/770-04-net-pcs-implement-Firmware-node-support-for-PCS-driv.patch:262]: Three prerequisite commits from the same upstream series (PR #23271) are missing, so this backport fixes the compile error but leaves airoha ethernet broken at runtime. This is the concrete form of what @robimarko raised above.

`fwnode_phylink_pcs_parse()` — introduced right here — returns `-ENODEV` unless the MAC fwnode has a `pcs-handle` property, and `fwnode_phylink_pcs_count()` below requires the referenced node to declare `#pcs-cells`. Three things in `openwrt-25.12` do not satisfy that:

1. The DTS still uses the old property name: [`an7581.dtsi:926`](https://github.com/openwrt/openwrt/blob/d9e40b05ee0246cce18bf08e91d8d5e16f9a9de9/target/linux/airoha/dts/an7581.dtsi#L926) / [`:934`](https://github.com/openwrt/openwrt/blob/d9e40b05ee0246cce18bf08e91d8d5e16f9a9de9/target/linux/airoha/dts/an7581.dtsi#L934) and [`an7583.dtsi:670`](https://github.com/openwrt/openwrt/blob/d9e40b05ee0246cce18bf08e91d8d5e16f9a9de9/target/linux/airoha/dts/an7583.dtsi#L670) / [`:678`](https://github.com/openwrt/openwrt/blob/d9e40b05ee0246cce18bf08e91d8d5e16f9a9de9/target/linux/airoha/dts/an7583.dtsi#L678) all say `pcs = <&…>`, not `pcs-handle = <&…>`.
2. The `pon_pcs` / `eth_pcs` nodes ([`an7581.dtsi:467`](https://github.com/openwrt/openwrt/blob/d9e40b05ee0246cce18bf08e91d8d5e16f9a9de9/target/linux/airoha/dts/an7581.dtsi#L467), [`:488`](https://github.com/openwrt/openwrt/blob/d9e40b05ee0246cce18bf08e91d8d5e16f9a9de9/target/linux/airoha/dts/an7581.dtsi#L488)) have no `#pcs-cells`.
3. Nothing registers a PCS provider. `310-09` in this branch is still the legacy implementation exporting [`airoha_pcs_create()`](``https://github.com/openwrt/openwrt/blob/d9e40b05ee0246cce18bf08e91d8d5e16f9a9de9/target/linux/airoha/patches-6.12/310-09-net-pcs-airoha-add-PCS-driver-for-Airoha-SoC.patch#L907)`` / `airoha_pcs_destroy()`; `fwnode_pcs_add_provider()` has no caller anywhere under `target/linux/`. Meanwhile [`310-10` line 248](``https://github.com/openwrt/openwrt/blob/d9e40b05ee0246cce18bf08e91d8d5e16f9a9de9/target/linux/airoha/patches-6.12/310-10-net-airoha-add-phylink-support.patch#L248)`` already calls `fwnode_phylink_pcs_parse()` and bails on error, so `airoha_setup_phylink()` will fail for GDM2/GDM4.

The commits that close these gaps, in upstream order between the two `generic:` commits already picked here:

- [`c5427d4cbea11c1ee3c1a3a66d4b3ff3909468db`](https://github.com/openwrt/openwrt/commit/c5427d4cbea11c1ee3c1a3a66d4b3ff3909468db) — "airoha: migrate to PCS standalone implementation" (rewrites `310-09` onto the fwnode provider API)
- [`4d5f579a8120eaea6b485ed07e8e7d96f2a891f9`](https://github.com/openwrt/openwrt/commit/4d5f579a8120eaea6b485ed07e8e7d96f2a891f9) — "airoha: update PCS node in DTSI for new PCS implementation" (adds `#pcs-cells`)
- [`953f1aaa93f442e03189879f83317b56805a1e3f`](https://github.com/openwrt/openwrt/commit/953f1aaa93f442e03189879f83317b56805a1e3f) — "airoha: update ethernet node for new PCS implementation" (`pcs` → `pcs-handle`)

Note `c5427d4` also renames the PCS `reg-names` (`xfi_mac` → `pcs_mac`, …), so it and `4d5f579a` have to land together.

Have the GDM2/GDM4 links been brought up on hardware with this series as-is? If they have, I'd like to understand what I'm reading wrong here.

---
_Generated by [Claude Code](https://claude.ai/code)_

File: target/linux/generic/backport-6.12/601-v7.1-net-add-netdev_from_priv-helper.patch [hunk 2]
```diff
@@ -0,0 +1,35 @@
...
+Signed-off-by: Qingfang Deng <dqfext@gmail.com>
+Link: https://patch.msgid.link/20260320075605.490832-1-dqfext@gmail.com
+Signed-off-by: Jakub Kicinski <kuba@kernel.org>
+---
+ include/linux/netdevice.h | 11 +++++++++++
+ 1 file changed, 11 insertions(+)
+
+--- a/include/linux/netdevice.h
++++ b/include/linux/netdevice.h
+@@ -2605,6 +2605,17 @@ static inline void *netdev_priv(const st
```
Comment (openwrt-ai) [inline target/linux/generic/backport-6.12/601-v7.1-net-add-netdev_from_priv-helper.patch:18]: nit: this is the one line that deviates from the cherry-picked upstream commit, and the commit message doesn't say so. [`cdb3dee613d1c0aea5236e8b7cbcdfa984c80ba9`](https://github.com/openwrt/openwrt/commit/cdb3dee613d1c0aea5236e8b7cbcdfa984c80ba9) adds this patch as `target/linux/generic/backport-6.18/601-…` with hunk header `@@ -2750,6 +2750,17 @@`; here it is placed under `backport-6.12/` and re-anchored to 2605. The retarget itself is right for this branch (7 airoha patches in `openwrt-25.12` reference `netdev_from_priv`), but a bare `(cherry picked from commit …)` trailer advertises a verbatim pick — worth a line in the body noting the patch was moved from `backport-6.18/` to `backport-6.12/` and re-anchored.

Minor, and separate: `netdev_priv()` sits at line 2603 in vanilla v6.12.103, so the `-2605` start is off by one against the pristine tree. `patch` absorbs that as fuzz, but a `make target/linux/refresh` with an airoha config selected would normalise it.

---
_Generated by [Claude Code](https://claude.ai/code)_

**Review by openwrt-ai — COMMENTED** [review]
Re-reviewed after the force-push: the single hand-rolled commit was replaced by 3 proper `-x` cherry-picks, which addresses the provenance point from the previous review. Verified each against its upstream commit on `main`.

- `d3863da1` vs [`e90f3f1f5a`](https://github.com/openwrt/openwrt/commit/e90f3f1f5ac8313a8c6106ad141c6f04fe0fa387) — identical file set (including the `310-08` → `pending-6.12/770-07` rename); the only textual differences are hunk offsets shifted by one, from `phylink.c` differing by a line on this branch.
- `4c9f1ddd` vs [`627cd79e1c`](https://github.com/openwrt/openwrt/commit/627cd79e1cdc5a93fd81b90ab78beabdb026a82e) — the dropped `pending-6.18/`, `mediatek/patches-6.18/` and airoha hunks are all correct omissions: this branch is 6.12-only, and `310-10` here already carries the `.fill_available_pcs` form. The re-anchoring inside `770-02` (the `pcs_changed` removal and the blank line trade places) produces a byte-identical post-patch file.
- `d9e40b05` vs [`cdb3dee613`](https://github.com/openwrt/openwrt/commit/cdb3dee613d1c0aea5236e8b7cbcdfa984c80ba9) — retargeted `backport-6.18/` → `backport-6.12/`; see inline.

The substantive finding is inline on `770-04`: three prerequisite commits from the same upstream series are missing, so this fixes the `linux/pcs/pcs.h` build failure but leaves the airoha PCS consumer/provider wiring incomplete on this branch.

## Commit checks

- `d3863da1` "generic: backport PCS standalone feature" — subject drops the `6.12:` scope from the upstream subject ("generic: 6.12: backport PCS standalone feature"). On `main` that prefix distinguishes the 6.12 and 6.18 variants of the same work; since this branch is 6.12-only it is arguably redundant, but keeping the upstream subject verbatim makes the pick easier to trace.
- `d9e40b05` "generic: backport netdev_from_priv() helper" — same, drops `6.18:`. Here the prefix change is load-bearing rather than cosmetic, because the patch really was moved to a different kernel series; the body should say so. Details inline.
- `4c9f1ddd` "generic: update pending PCS patch with .fill_available_pcs OP" — message matches the diff.

Also note the PR description still describes the previous approach ("This patch implements a second way. Missed patches were taken from upsream openwrt."), which no longer matches the three cherry-picked commits; and per the comment from @YaleiZang, #24823 may already cover this ground.

---
_Generated by [Claude Code](https://claude.ai/code)_
