### PR TITLE
[23.05] toolchain/gdb: backport patch for macOS to fix invalid range

### PR DESCRIPTION
**Pull request by BKPepe**
With the recent macOS update to Ventura, it looks like gdb could not be compiled with clang16 and newer version, because it fails with: 
```
./../gdbsupport/enum-flags.h:95:52: error: integer value -1 is outside the valid range of values [0, 15] for this enumeration type [-Wenum-constexpr-conversion]
    integer_for_size<sizeof (T), static_cast<bool>(T (-1) < T (0))>::type
                                                   ^
./../gdbsupport/enum-flags.h:95:52: error: integer value -1 is outside the valid range of values [0, 1] for this enumeration type [-Wenum-constexpr-conversion] ./../gdbsupport/enum-flags.h:95:52: error: integer value -1 is outside the valid range of values [0, 3] for this enumeration type [-Wenum-constexpr-conversion] ./../gdbsupport/enum-flags.h:95:52: error: integer value -1 is outside the valid range of values [0, 3] for this enumeration type [-Wenum-constexpr-conversion] 4 errors generated.
```

- Upstream bug: https://sourceware.org/bugzilla/show_bug.cgi?id=30423

- Backported upstream commit: https://sourceware.org/git/?p=binutils-gdb.git;a=commit;h=ae61525fcf456ab395d55c45492a106d1275873a

Fixes: https://github.com/openwrt/openwrt/issues/15314
(unfortunately only for OpenWrt 23.05, it does not work with OpenWrt 22.03)

Refreshed with quilt.

### CODE REVIEW

**Comment by olivier-lu** [comment]
Hi,
I am trying to compile v23.05.3 on macOS 14.5 but I am still getting the error eventhough, I see that patch file at toolchain/gdb/patches/0001-gdbsupport-ignore-Wenum-constexpr-conversion-in-enum.patch

This is the error I am seeing:

``
make[6]: Entering directory '/Volumes/OpenWrt-23.05/openwrt/build_dir/toolchain-arm_cortex-a9_gcc-12.3.0_musl_eabi/gdb-12.1/gdb'
g++ -x c++ -std=gnu++11   -I. -I. -I./config -DLOCALEDIR="\"/Volumes/OpenWrt-23.05/openwrt/staging_dir/toolchain-arm_cortex-a9_gcc-12.3.0_musl_eabi/share/locale\"" -DHAVE_CONFIG_H -I./../include/opcode -I./../readline/readline/.. -I./../zlib -I../bfd -I./../bfd -I./../include -I../libdecnumber -I./../libdecnumber -I./../intl -I./../gnulib/import -I../gnulib/import -I./.. -I.. -I./../libbacktrace/ -I../libbacktrace/  -DTUI=1 -I/Volumes/OpenWrt-23.05/openwrt/staging_dir/host/include    -I./.. -pthread  -Wall -Wpointer-arith -Wno-unused -Wunused-value -Wunused-function -Wno-switch -Wno-char-subscripts -Wempty-body -Wunused-but-set-parameter -Wunused-but-set-variable -Wno-sign-compare -Wno-mismatched-tags -Wno-error=deprecated-register -Wsuggest-override -Wdeprecated-copy -Wdeprecated-copy-dtor -Wredundant-move -Wmissing-declarations -Wmissing-prototypes -Wformat -Wformat-nonliteral   -c -o gdb.o -MT gdb.o -MMD -MP -MF ./.deps/gdb.Tpo gdb.c
In file included from gdb.c:19:
In file included from ./defs.h:65:
./../gdbsupport/enum-flags.h:95:52: error: integer value -1 is outside the valid range of values [0, 15] for this enumeration type [-Wenum-constexpr-conversion]
    integer_for_size<sizeof (T), static_cast<bool>(T (-1) < T (0))>::type
                                                   ^
1 error generated.
make[6]: *** [Makefile:1655: gdb.o] Error 1
make[6]: Leaving directory '/Volumes/OpenWrt-23.05/openwrt/build_dir/toolchain-arm_cortex-a9_gcc-12.3.0_musl_eabi/gdb-12.1/gdb'
make[5]: *** [Makefile:11484: all-gdb] Error 2
make[5]: Leaving directory '/Volumes/OpenWrt-23.05/openwrt/build_dir/toolchain-arm_cortex-a9_gcc-12.3.0_musl_eabi/gdb-12.1'
make[4]: *** [Makefile:1030: all] Error 2
make[4]: Leaving directory '/Volumes/OpenWrt-23.05/openwrt/build_dir/toolchain-arm_cortex-a9_gcc-12.3.0_musl_eabi/gdb-12.1'
make[3]: *** [Makefile:75: /Volumes/OpenWrt-23.05/openwrt/build_dir/toolchain-arm_cortex-a9_gcc-12.3.0_musl_eabi/gdb-12.1/.built] Error 2
make[3]: Leaving directory '/Volumes/OpenWrt-23.05/openwrt/toolchain/gdb'
time: toolchain/gdb/compile#1.40#0.46#2.27
    ERROR: toolchain/gdb failed to build.
make[2]: *** [toolchain/Makefile:93: toolchain/gdb/compile] Error 1
make[2]: Leaving directory '/Volumes/OpenWrt-23.05/openwrt'
make[1]: *** [toolchain/Makefile:89: /Volumes/OpenWrt-23.05/openwrt/staging_dir/toolchain-arm_cortex-a9_gcc-12.3.0_musl_eabi/stamp/.toolchain_compile] Error 2
make[1]: Leaving directory '/Volumes/OpenWrt-23.05/openwrt'
make: *** [/Volumes/OpenWrt-23.05/openwrt/include/toplevel.mk:232: world] Error 2
``

Any idea why the patch didn't work for me?
