### ISSUE TITLE
util-linux: musl build fails with "AT_HANDLE_FID undeclared" in sys-utils/nsenter.c

### ISSUE THREAD

**Issue by xuanranran** [openwrt/openwrt#23058]
### Describe the bug

After commit 1a1bdcdc2ad22b9f181a9efd05bf451c3936c0cb (`util-linux: update to 2.42`), building `package/utils/util-linux` fails on all musl targets because `sys-utils/nsenter.c` references `AT_HANDLE_FID` without a fallback definition.

`AT_HANDLE_FID` is a Linux 6.5 / glibc 2.39+ symbol. **musl libc does not define it**, even though `linux/nsfs.h` (providing `struct nsfs_file_handle`) is present, which is enough for the meson feature gate `HAVE_STRUCT_NSFS_FILE_HANDLE && HAVE_PIDFD_OPEN` to enable the `USE_NAMESPACE_ID_SUPPORT` code path.

Error:

```
../sys-utils/nsenter.c: In function 'fill_nsfs_file_handle':
../sys-utils/nsenter.c:223:47: error: 'AT_HANDLE_FID' undeclared (first use in this function)
  223 |                               AT_EMPTY_PATH | AT_HANDLE_FID) == -1)
      |                                               ^~~~~~~~~~~~~
```

This is already fixed upstream in util-linux by commit `5452239f6e` (“nsenter: Fix AT_HANDLE_FID on musl”), which simply adds a fallback macro:

```c
#ifndef AT_HANDLE_FID
# define AT_HANDLE_FID 0x200
#endif
```

https://github.com/util-linux/util-linux/commit/5452239f6e69d2d3aaa427d2d2253247cfb7cb7b

Please backport this as [package/utils/util-linux/patches/0002-nsenter-Fix-AT_HANDLE_FID-on-musl.patch](cci:7://file:///D:/App%20Data/Github/immortalwrt/package/utils/util-linux/patches/0002-nsenter-Fix-AT_HANDLE_FID-on-musl.patch:0:0-0:0) until util-linux 2.43 is released.

### OpenWrt version

master, any commit after 0d21956ecdade023981d46eb8f059c3e6a3d00be

### OpenWrt release

SNAPSHOT

### OpenWrt target/subtarget

x86/64

### Device

N/A (build-time failure, toolchain/host-side)

### Image kind

Self-built image

### Steps to reproduce

1. `git clone https://github.com/openwrt/openwrt.git && cd openwrt`
2. `git checkout master` (or any commit ≥ 1a1bdcdc2ad)
3. `./scripts/feeds update -a && ./scripts/feeds install -a`
4. `make defconfig` with `CONFIG_TARGET_x86_64=y` (or any musl target)
5. `make package/utils/util-linux/{clean,compile} V=s`

### Actual behaviour

Build aborts with:

```
../sys-utils/nsenter.c:223:47: error: 'AT_HANDLE_FID' undeclared (first use in this function)
ninja: build stopped: subcommand failed.
make[2]: *** [Makefile:1049: .../util-linux-2.42/.built] Error 1
ERROR: package/utils/util-linux failed to build.
```

### Expected behaviour

util-linux 2.42 compiles cleanly on musl targets.

### Additional info

- Upstream fix (ready to apply as-is): https://github.com/util-linux/util-linux/commit/5452239f6e69d2d3aaa427d2d2253247cfb7cb7b.patch
- Regression introduced in: 1a1bdcdc2ad22b9f181a9efd05bf451c3936c0cb
- Affects: all musl targets (x86_64, aarch64, mipsel, etc.)
- glibc targets (x86_64/glibc, etc.) are not affected since glibc ≥ 2.39 defines `AT_HANDLE_FID`.

### Diffconfig

```text
# default defconfig for x86/64 reproduces; no custom diffconfig required
CONFIG_TARGET_x86=y
CONFIG_TARGET_x86_64=y
CONFIG_TARGET_x86_64_DEVICE_generic=y
```

### Terms

- [x] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by xuanranran** [comment]
@t-8ch Please take a look.

**Comment by smalleaves** [comment]
I encountered the same error when compiling the firmware after syncing the code today on the Mediatek platform.


`../sys-utils/nsenter.c: In function 'fill_nsfs_file_handle':
../sys-utils/nsenter.c:223:47: error: 'AT_HANDLE_FID' undeclared (first use in this function)
  223 |                               AT_EMPTY_PATH | AT_HANDLE_FID) == -1)
      |                                               ^~~~~~~~~~~~~
../sys-utils/nsenter.c:223:47: note: each undeclared identifier is reported only once for each function it appears in
ninja: build stopped: subcommand failed.`

**Comment by t-8ch** [comment]
This only happens with 6.18 kernels. IMO the CI should be extended to also test CONFIG_TESTING_KERNEL=y.
Fixed by #23059

> no custom diffconfig required

>  [x] I am reporting an issue for OpenWrt, not an unsupported fork.

https://github.com/xuanranran/OpenWRT-X86_64/commit/f2af5394805e853e53c677f05c9fb358a42a8a14 ?

**Comment by xuanranran** [comment]
> This only happens with 6.18 kernels. IMO the CI should be extended to also test CONFIG_TESTING_KERNEL=y. Fixed by [#23059](https://github.com/openwrt/openwrt/pull/23059)
> 
> > no custom diffconfig required
> 
> > [x] I am reporting an issue for OpenWrt, not an unsupported fork.
> 
> [xuanranran/OpenWRT-X86_64@f2af539](https://github.com/xuanranran/OpenWRT-X86_64/commit/f2af5394805e853e53c677f05c9fb358a42a8a14) ?

The util-linux source code project has a commit for fixing a musl compilation issue. After using this patch, named 0001-nsenter-Fix-AT_HANDLE_FID-on-musl.patch, my OpenWrt compilation process succeeded. However, this is unrelated to my OpenWrt compilation project. Util-linux version 2.42 should also fail to compile on the 6.12 kernel. Please use this patch in version 2.42 for now and remove it after version 2.43 is released.

**Comment by t-8ch** [comment]
> Util-linux version 2.42 should also fail to compile on the 6.12 kernel. 

"should"? Did you test it? I did and it didn't reproduce the issue.
There is no need to make stuff up. It just wastes everybody's time.

**Comment by xuanranran** [comment]
> > Util-linux version 2.42 should also fail to compile on the 6.12 kernel.
> 
> "should"? Did you test it? I did and it didn't reproduce the issue. There is no need to make stuff up. It just wastes everybody's time.

This problem is not complicated, and the solution is simple. Furthermore, OpenWrt is gradually starting to support kernel 6.18 and is gradually dropping support for kernel 6.12. Let's leave it at that for now until util-linux 2.43 is released.

**Comment by t-8ch** [comment]
I never disputed the complexity of the problem or that fact that it should be fixed.
But I wasted a bunch of my lunch break reproducing this issue as the provided information was willfully incorrect. If that incorrect information was not there, or you reproduced this on vanilla OpenWrt, as the issue template requires, it would have been easier.

Maybe you notice how I did not complain about the report from @smalleaves. Their report contains less information than yours, but I see which information is missing and can account for that.

**Comment by xuanranran** [comment]
> I never disputed the complexity of the problem or that fact that it should be fixed. But I wasted a bunch of my lunch break reproducing this issue as the provided information was willfully incorrect. If that incorrect information was not there, or you reproduced this on vanilla OpenWrt, as the issue template requires, it would have been easier.
> 
> Maybe you notice how I did not complain about the report from [@smalleaves](https://github.com/smalleaves). Their report contains less information than yours, but I see which information is missing and can account for that.

Okay, I should have explained it in more detail.

**Comment by t-8ch** [comment]
*Not* "more" detail. The original report had enough information. Just none of the made-up stuff.
