### PR TITLE
tools/libelf: remove unneeded host library

### PR DESCRIPTION
**Pull request by guidosarducci**
### Description:
This old ELF library dating to 2009 used to be necessary on MacOS but is not required for building the kernel or tools since [1]. On Linux systems, libelf is already an OpenWRT build-system prerequisite [2].

Presence of the older library can mask or conflict with the system libelf and lead to build errors, as seen compiling Linux kernels since v5.8 or host tools such as dwarves (e.g. pahole).

Remove the unnecessary tools/libelf library and avoid the related issues.

[1] 5f8e587240 ("build: force disable stack validation during kernel build on non-linux systems")
[2] https://openwrt.org/docs/guide-developer/build-system/install-buildsystem#prerequisites

Tested-by: Rosen Penev <rosenp@gmail.com> (Linux)
Tested-by: Georgi Valkov <gvalkov@abv.bg> (MacOS)
Signed-off-by: Tony Ambardar <itugrok@yahoo.com>

### History:
The removal of `tools/libelf` has been previously discussed in https://github.com/openwrt/packages/issues/9927 and #3855, and this PR is carved out of the latter's ELF library cleanups alongside PR #3982. These cleanups are important in building other host tools dependent on `libelf` as well as recent Linux kernels ().

### Distribution/Testing:
@neheb and I have both tested builds with `tools/libelf` removal on Linux systems, while @httpstorm has done the same for MacOS based builds. @ldir-EDB0 should be interested in MacOS changes, and has also reviewed #3982 along with @luizluca and @curtdept.

Some folks following #3855 who may be interested in this PR include: @PolynomialDivision and @arkap.

### CODE REVIEW

**Comment by ldir-EDB0** [comment]
Thanks! Pulled into my staging tree at https://git.openwrt.org/openwrt/staging/ldir.git

**Comment by guidosarducci** [comment]
Again, thank you, Kevin.

One thing worth mentioning is that build artifacts from `tools/libelf` may still remain unless one does a `make dirclean` or, alternatively, runs `make tools/libelf/clean` *before* applying this commit.

**Comment by jmarcet** [comment]
In a clean built tree I'm getting this error:

```
  x86_64-openwrt-linux-musl-gcc -Wp,-MMD,init/.main.o.d  -nostdinc -isystem /home/jmarcet/src/openwrt-master-x64/@build/staging_dir/toolchain-x86_64_gcc-10.2.0_musl/bin/../lib/gcc/x86_64-openwrt-linux-musl/10.2.0/include -I./arch/x86/include -I./arch/x86/include/generated  -I./include -I./arch/x86/include/uapi -I./arch/x86/include/generated/uapi -I./include/uapi -I./include/g
enerated/uapi -include ./include/linux/kconfig.h -include ./include/linux/compiler_types.h -D__KERNEL__ -fmacro-prefix-map=./= -Wall -Wundef -Werror=strict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -fshort-wchar -fno-PIE -Werror=implicit-function-declaration -Werror=implicit-int -Werror=return-type -Wno-format-security -std=gnu89 -mno-sse -mno-mmx -mno-sse2 -
mno-3dnow -mno-avx -fcf-protection=none -m64 -falign-jumps=1 -falign-loops=1 -mno-80387 -mno-fp-ret-in-387 -mpreferred-stack-boundary=3 -mskip-rax-setup -march=core2 -mno-red-zone -mcmodel=kernel -Wno-sign-compare -fno-asynchronous-unwind-tables -mindirect-branch=thunk-extern -mindirect-branch-register -fno-jump-tables -fno-delete-null-pointer-checks -Wno-frame-address -Wno-f
ormat-truncation -Wno-format-overflow -Wno-address-of-packed-member -O2 -fno-caller-saves -fno-allow-store-data-races -fno-reorder-blocks -fno-ipa-cp-clone -fno-partial-inlining -Wframe-larger-than=1024 -fstack-protector-strong -Wno-unused-but-set-variable -Wimplicit-fallthrough -Wno-unused-const-variable -fno-omit-frame-pointer -fno-optimize-sibling-calls -g -gdwarf-4 -Wdecl
aration-after-statement -Wvla -Wno-pointer-sign -Wno-stringop-truncation -Wno-zero-length-bounds -Wno-array-bounds -Wno-stringop-overflow -Wno-restrict -Wno-maybe-uninitialized -fno-strict-overflow -fno-stack-check -fconserve-stack -Werror=date-time -Werror=incompatible-pointer-types -Werror=designated-init -Wno-packed-not-aligned -ffile-prefix-map=/home/jmarcet/src/openwrt-m
aster-x64/build_dir/target-x86_64_musl=target-x86_64_musl -fno-function-sections -fno-data-sections    -DKBUILD_MODFILE='"init/main"' -DKBUILD_BASENAME='"main"' -DKBUILD_MODNAME='"main"' -c -o init/main.o init/main.c                                                                                                                                                                  
  /home/jmarcet/src/openwrt-master-x64/staging_dir/host/bin/sparse -D__linux__ -Dlinux -D__STDC__ -Dunix -D__unix__ -Wbitwise -Wno-return-void -Wno-unknown-attribute  -D__x86_64__ --arch=x86 -mlittle-endian -m64 -Wp,-MMD,init/.main.o.d  -nostdinc -isystem /home/jmarcet/src/openwrt-master-x64/@build/staging_dir/toolchain-x86_64_gcc-10.2.0_musl/bin/../lib/gcc/x86_64-openwrt-lin
ux-musl/10.2.0/include -I./arch/x86/include -I./arch/x86/include/generated  -I./include -I./arch/x86/include/uapi -I./arch/x86/include/generated/uapi -I./include/uapi -I./include/generated/uapi -include ./include/linux/kconfig.h -include ./include/linux/compiler_types.h -D__KERNEL__ -fmacro-prefix-map=./= -Wall -Wundef -Werror=strict-prototypes -Wno-trigraphs -fno-strict-alia
sing -fno-common -fshort-wchar -fno-PIE -Werror=implicit-function-declaration -Werror=implicit-int -Werror=return-type -Wno-format-security -std=gnu89 -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -mno-avx -fcf-protection=none -m64 -falign-jumps=1 -falign-loops=1 -mno-80387 -mno-fp-ret-in-387 -mpreferred-stack-boundary=3 -mskip-rax-setup -march=core2 -mno-red-zone -mcmodel=kernel -W
no-sign-compare -fno-asynchronous-unwind-tables -mindirect-branch=thunk-extern -mindirect-branch-register -fno-jump-tables -fno-delete-null-pointer-checks -Wno-frame-address -Wno-format-truncation -Wno-format-overflow -Wno-address-of-packed-member -O2 -fno-caller-saves -fno-allow-store-data-races -fno-reorder-blocks -fno-ipa-cp-clone -fno-partial-inlining -Wframe-larger-than=
1024 -fstack-protector-strong -Wno-unused-but-set-variable -Wimplicit-fallthrough -Wno-unused-const-variable -fno-omit-frame-pointer -fno-optimize-sibling-calls -g -gdwarf-4 -Wdeclaration-after-statement -Wvla -Wno-pointer-sign -Wno-stringop-truncation -Wno-zero-length-bounds -Wno-array-bounds -Wno-stringop-overflow -Wno-restrict -Wno-maybe-uninitialized -fno-strict-overflow 
-fno-stack-check -fconserve-stack -Werror=date-time -Werror=incompatible-pointer-types -Werror=designated-init -Wno-packed-not-aligned -ffile-prefix-map=/home/jmarcet/src/openwrt-master-x64/build_dir/target-x86_64_musl=target-x86_64_musl -fno-function-sections -fno-data-sections    -DKBUILD_MODFILE='"init/main"' -DKBUILD_BASENAME='"main"' -DKBUILD_MODNAME='"main"' init/main.c
./include/linux/compiler_types.h:14:55: error: undefined identifier '__user'                                                                                                                                                                                                                                                                                                              
./include/linux/compiler_types.h:14:55: error: bad constant expression type                                                                                                                                                                                                                                                                                                               
./include/linux/compiler_types.h:15:53: error: undefined identifier '__iomem'                                                                                                                                                                                                                                                                                                             
./include/linux/compiler_types.h:15:53: error: bad constant expression type                                                                                                                                                                                                                                                                                                               
./include/asm-generic/rwonce.h:67:16: error: typename in expression                                                                                                                                                                                                                                                                                                                       
./include/asm-generic/rwonce.h:67:16: error: Expected ) in function call                                                                                                                                                                                                                                                                                                                  
./include/asm-generic/rwonce.h:67:16: error: got :                                                                                                                                                                                                                                                                                                                                        
./include/linux/instrumented.h:116:30: error: undefined identifier '__user'                                                                                                                                                                                                                                                                                                               
./include/linux/instrumented.h:116:30: error: bad constant expression type                                                                                                                                                                                                                                                                                                                
./include/linux/instrumented.h:133:54: error: undefined identifier '__user'                                                                                                                                                                                                                                                                                                               
./include/linux/instrumented.h:133:54: error: bad constant expression type                                                                                                                                                                                                                                                                                                                
./include/linux/kernel.h:421:49: error: undefined identifier '__user'                                                                                                                                                                                                                                                                                                                     
./include/linux/kernel.h:421:49: error: bad constant expression type                                                                                                                                                                                                                                                                                                                      
./include/linux/kernel.h:422:48: error: undefined identifier '__user'                                                                                                                                                                                                                                                                                                                     
./include/linux/kernel.h:422:48: error: bad constant expression type                                                                                                                                                                                                                                                                                                                      
./include/linux/kernel.h:423:48: error: undefined identifier '__user'                                                                                                                                                                                                                                                                                                                     
./include/linux/kernel.h:423:48: error: bad constant expression type                                                                                                                                                                                                                                                                                                                      
./include/linux/kernel.h:424:47: error: undefined identifier '__user'                                                                                                                                                                                                                                                                                                                     
./include/linux/kernel.h:424:47: error: bad constant expression type                                                                                                                                                                                                                                                                                                                      
./include/linux/kernel.h:425:50: error: undefined identifier '__user'                                                                                                                                                                                                                                                                                                                     
./include/linux/kernel.h:425:50: error: bad constant expression type                                                                                                                                                                                                                                                                                                                      
./include/linux/kernel.h:426:49: error: undefined identifier '__user'                                                                                                                                                                                                                                                                                                                     
./include/linux/kernel.h:426:49: error: bad constant expression type                                                                                                                                                                                                                                                                                                                      
./include/linux/kernel.h:427:49: error: undefined identifier '__user'                                                                                                                                                                                                                                                                                                                     
./include/linux/kernel.h:427:49: error: bad constant expression type                                                                                                                                                                                                                                                                                                                      
./include/linux/kernel.h:428:49: error: undefined identifier '__user'                                                                                                                                                                                                                                                                                                                     
./include/linux/kernel.h:428:49: error: bad constant expression type                                                                                                                                                                                                                                                                                                                      
./include/linux/kernel.h:429:48: error: undefined identifier '__user'                                                                                                                                                                                                                                                                                                                     
./include/linux/kernel.h:429:48: error: bad constant expression type                                                                                                                                                                                                                                                                                                                      
./include/linux/kernel.h:430:48: error: undefined identifier '__user'                                                                                                                                                                                                                                                                                                                     
./include/linux/kernel.h:430:48: error: bad constant expression type                                                                                                                                                                                                                                                                                                                      
./include/linux/kernel.h:431:50: error: undefined identifier '__user'                                                                                                                                                                                                                                                                                                                     
./include/linux/kernel.h:431:50: error: bad constant expression type                                                                                                                                                                                                                                                                                                                      
./include/linux/kernel.h:433:63: error: undefined identifier '__user'                                                                                                                                                                                                                                                                                                                     
./include/linux/kernel.h:433:63: error: bad constant expression type                                                                                                                                                                                                                                                                                                                      
./include/linux/kernel.h:438:63: error: undefined identifier '__user'                                                                                                                                                                                                                                                                                                                     
./include/linux/kernel.h:438:63: error: bad constant expression type                                                                                                                                                                                                                                                                                                                      
./include/linux/kernel.h:443:63: error: undefined identifier '__user'                                                                                                                                                                                                                                                                                                                     
./include/linux/kernel.h:443:63: error: bad constant expression type                                                                                                                         
./include/linux/kernel.h:448:63: error: undefined identifier '__user'                                                                                                                        
./include/linux/kernel.h:448:63: error: bad constant expression type                                                                                                                         
./include/linux/list.h:282:16: error: typename in expression                                  
./include/linux/list.h:282:16: error: Expected ) in function call                             
./include/linux/list.h:282:16: error: got :                                                   
./include/linux/list.h:318:34: error: typename in expression                                  
./include/linux/list.h:318:34: error: Expected ) in function call                             
./include/linux/list.h:318:34: error: got :                                                   
./include/linux/list.h:821:17: error: typename in expression                                  
./include/linux/list.h:821:17: error: Expected ) in function call                             
./include/linux/list.h:821:17: error: got :                                                   
./include/linux/list.h:830:17: error: typename in expression                                  
./include/linux/list.h:830:17: error: Expected ) in function call                             
./include/linux/list.h:830:17: error: got :                                                   
./include/linux/time.h:12:48: error: undefined identifier '__user'                            
./include/linux/time.h:12:48: error: bad constant expression type                             
./include/linux/time.h:14:42: error: undefined identifier '__user'                            
./include/linux/time.h:14:42: error: bad constant expression type                             
./include/linux/time.h:16:58: error: undefined identifier '__user'                            
./include/linux/time.h:16:58: error: bad constant expression type                             
./include/linux/time.h:18:52: error: undefined identifier '__user'                            
./include/linux/time.h:18:52: error: bad constant expression type                             
./include/linux/time.h:43:43: error: undefined identifier '__user'                            
./include/linux/time.h:43:43: error: bad constant expression type                             
./arch/x86/include/asm/segment.h:262:9: error: Expected ( after asm
./arch/x86/include/asm/segment.h:262:9: error: got __inline
./arch/x86/include/asm/atomic.h:29:16: error: typename in expression
./arch/x86/include/asm/atomic.h:29:16: error: Expected ) in function call
./arch/x86/include/asm/atomic.h:29:16: error: got :
./arch/x86/include/asm/atomic64_64.h:22:16: error: typename in expression
./arch/x86/include/asm/atomic64_64.h:22:16: error: Expected ) in function call
./arch/x86/include/asm/atomic64_64.h:22:16: error: got :
./include/linux/atomic-arch-fallback.h:84:16: error: typename in expression
./include/linux/atomic-arch-fallback.h:84:16: error: Expected ) in function call
./include/linux/atomic-arch-fallback.h:84:16: error: got :
./include/linux/atomic-arch-fallback.h:1191:16: error: typename in expression
./include/linux/atomic-arch-fallback.h:1191:16: error: Expected ) in function call
./include/linux/atomic-arch-fallback.h:1191:16: error: got :
./include/linux/jump_label.h:278:9: error: Expected ( after asm
./include/linux/jump_label.h:278:9: error: got __inline
./include/linux/jump_label.h:284:9: error: Expected ( after asm
./include/linux/jump_label.h:284:9: error: got __inline
./include/linux/jump_label.h:306:9: error: Expected ( after asm
./include/linux/jump_label.h:306:9: error: got __inline
./include/linux/jump_label.h:309:17: error: Expected ( after asm
./include/linux/jump_label.h:309:17: error: got __inline
./include/linux/jump_label.h:317:9: error: Expected ( after asm
./include/linux/jump_label.h:317:9: error: got __inline
./include/linux/jump_label.h:320:17: error: Expected ( after asm
./include/linux/jump_label.h:320:17: error: got __inline
./arch/x86/include/asm/ptrace.h:362:48: error: undefined identifier '__user'
./arch/x86/include/asm/ptrace.h:362:48: error: bad constant expression type
./arch/x86/include/asm/ptrace.h:364:48: error: undefined identifier '__user'
./arch/x86/include/asm/ptrace.h:364:48: error: bad constant expression type
./arch/x86/include/asm/percpu.h:359:45: error: undefined identifier '__percpu'
./arch/x86/include/asm/percpu.h:359:45: error: bad constant expression type
./arch/x86/include/asm/percpu.h:361:23: error: undefined identifier '__percpu'
./arch/x86/include/asm/percpu.h:361:23: error: bad constant expression type
./arch/x86/include/asm/percpu.h:362:32: error: undefined identifier '__percpu'
./arch/x86/include/asm/percpu.h:362:32: error: bad constant expression type
./arch/x86/include/asm/percpu.h:372:45: error: undefined identifier '__percpu'
./arch/x86/include/asm/percpu.h:372:45: error: bad constant expression type
./arch/x86/include/asm/percpu.h:379:48: error: too many errors
Segmentation fault
make[6]: *** [scripts/Makefile.build:279: init/main.o] Error 139
make[6]: *** Deleting file 'init/main.o'
make[5]: *** [Makefile:1801: init] Error 2
make[5]: Leaving directory '/home/jmarcet/src/openwrt-master-x64/@build/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.23'
make[4]: *** [Makefile:23: /home/jmarcet/src/openwrt-master-x64/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.23/.modules] Error 2
make[4]: Leaving directory '/home/jmarcet/src/openwrt-master-x64/target/linux/x86'
make[3]: *** [Makefile:11: compile] Error 2
make[3]: Leaving directory '/home/jmarcet/src/openwrt-master-x64/target/linux'
time: target/linux/compile#1.92#0.85#2.82
    ERROR: target/linux failed to build.
make[2]: *** [target/Makefile:25: target/linux/compile] Error 1
make[2]: Leaving directory '/home/jmarcet/src/openwrt-master-x64'
make[1]: *** [target/Makefile:18: /home/jmarcet/src/openwrt-master-x64/staging_dir/target-x86_64_musl/stamp/.target_compile] Error 2
make[1]: Leaving directory '/home/jmarcet/src/openwrt-master-x64'
make: *** [/home/jmarcet/src/openwrt-master-x64/include/toplevel.mk:230: world] Error 2

real    0m15.342s
user    0m12.320s
sys     0m3.172s
```

**Comment by httpstorm** [comment]
@jmarcet 
I assume you are building the x86_64 target? I just tried building bb95be9265a9e3eb71c4f50b5f289a75683405d4 from an empty directory.
It compiles correctly on both Ubuntu Linux 20.04 and macOS 11.
Try `make dirclean` or build from an empty directory and let us know if it makes any difference?
Tony also mentioned running `make tools/libelf/clean`. Note that `make clean` may not be sufficient.
